import { exactRadiusIdentity } from '../radius/radius-identity.js'
import type { ClassificationSnapshot, OperationalGroup, ProcessFamily, ProcessFamilyKey, RadiusStateClassification, OperationalGroupKey } from './models.js'

export const SEEDED_OPERATIONAL_GROUPS: OperationalGroup[] = [
  { id: 'radius-group-production', key: 'PRODUCTION', displayName: 'Production', description: 'Operator-entered Radius states associated with production activity.', lightColor: '#18864b', darkColor: '#39c978', icon: 'production', sortOrder: 10 },
  { id: 'radius-group-changeover-setup', key: 'CHANGEOVER_SETUP', displayName: 'Changeover & Setup', description: 'Make-ready and job setup activity.', lightColor: '#2563b8', darkColor: '#60a5fa', icon: 'changeover', sortOrder: 20 },
  { id: 'radius-group-routine-process', key: 'ROUTINE_PROCESS', displayName: 'Routine Process', description: 'Expected cleaning, material, and production-support processes.', lightColor: '#0f827b', darkColor: '#35c7bd', icon: 'process', sortOrder: 30 },
  { id: 'radius-group-adjustment-quality', key: 'ADJUSTMENT_QUALITY', displayName: 'Adjustment & Quality', description: 'Print adjustment and quality-related operator annotations.', lightColor: '#b46b09', darkColor: '#f2b84b', icon: 'quality', sortOrder: 40 },
  { id: 'radius-group-waiting-idle-hold', key: 'WAITING_IDLE_HOLD', displayName: 'Waiting, Idle & Hold', description: 'Neutral nonproduction, explicit waiting, approval, and hold states.', lightColor: '#8a6500', darkColor: '#d7b44a', icon: 'waiting', sortOrder: 50 },
  { id: 'radius-group-fault-recovery', key: 'FAULT_RECOVERY', displayName: 'Fault & Recovery', description: 'Explicit non-maintenance failure and recovery annotations.', lightColor: '#bd3535', darkColor: '#f06a6a', icon: 'fault', sortOrder: 60 },
  { id: 'radius-group-maintenance', key: 'MAINTENANCE_INTERVENTION', displayName: 'Maintenance Intervention', description: 'Explicit mechanical, electrical, or maintenance intervention.', lightColor: '#7546a8', darkColor: '#b58add', icon: 'maintenance', sortOrder: 70 },
  { id: 'radius-group-admin-unknown', key: 'ADMIN_UNKNOWN', displayName: 'Administrative & Unknown', description: 'Administrative, obsolete, empty, ambiguous, or not-yet-reviewed Radius identities.', lightColor: '#68727d', darkColor: '#9ca8b5', icon: 'unknown', sortOrder: 80 },
]

export const SEEDED_PROCESS_FAMILIES: ProcessFamily[] = [
  ['PRODUCTION', 'Production'], ['MAKE_READY', 'Make Ready'], ['CLEANING_WASH', 'Cleaning / Wash'], ['ROLL_MATERIAL', 'Roll / Material'],
  ['SLEEVES_PLATES', 'Sleeves / Plates'], ['ANILOX', 'Anilox'], ['DOCTOR_BLADE_CHAMBER', 'Doctor Blade / Chamber'], ['INK_COLOR', 'Ink / Color'],
  ['IMPRESSION_REGISTER_PRINT_QUALITY', 'Impression / Register / Print Quality'], ['SUBSTRATE', 'Substrate'], ['WEB_HANDLING_WEB_BREAK', 'Web Handling / Web Break'],
  ['QUALITY_APPROVAL', 'Quality / Approval'], ['MECHANICAL_ELECTRICAL', 'Mechanical / Electrical'], ['MAINTENANCE', 'Maintenance'],
  ['TRIAL_ADMINISTRATIVE', 'Trial / Administrative'], ['UNKNOWN', 'Unknown'],
].map(([key, displayName], index) => ({ id: `radius-family-${String(key).toLowerCase().replaceAll('_', '-')}`, key: key as ProcessFamilyKey, displayName, description: `${displayName} process family.`, sortOrder: (index + 1) * 10 }))

const groupByKey = new Map(SEEDED_OPERATIONAL_GROUPS.map((group) => [group.key, group]))
const familyByKey = new Map(SEEDED_PROCESS_FAMILIES.map((family) => [family.key, family]))

interface SeedIdentity { eventType: string; statusCode: string | null; statusDescription: string; group: OperationalGroupKey; family: ProcessFamilyKey; confidence?: 'HIGH' | 'MEDIUM' | 'LOW'; review?: boolean; obsolete?: boolean }

const seeds: SeedIdentity[] = [
  { eventType: 'G', statusCode: '20', statusDescription: 'Run', group: 'PRODUCTION', family: 'PRODUCTION' },
  { eventType: 'G', statusCode: '150', statusDescription: 'Run Production', group: 'PRODUCTION', family: 'PRODUCTION' },
  { eventType: 'M', statusCode: '16', statusDescription: 'Make Ready', group: 'CHANGEOVER_SETUP', family: 'MAKE_READY' },
  { eventType: 'M', statusCode: '47', statusDescription: 'Make Ready - Time Required to Setup Job', group: 'CHANGEOVER_SETUP', family: 'MAKE_READY' },
  { eventType: 'M', statusCode: '47-1', statusDescription: 'Make-Ready Sleeves', group: 'CHANGEOVER_SETUP', family: 'SLEEVES_PLATES' },
  { eventType: 'M', statusCode: '48', statusDescription: 'Make Ready Sleeves', group: 'CHANGEOVER_SETUP', family: 'SLEEVES_PLATES' },
  { eventType: 'M', statusCode: '80', statusDescription: 'Anilox: Change', group: 'ROUTINE_PROCESS', family: 'ANILOX' },
  { eventType: 'B', statusCode: '82', statusDescription: 'Dr. Blade Change', group: 'ROUTINE_PROCESS', family: 'DOCTOR_BLADE_CHAMBER' },
  { eventType: 'B', statusCode: '145-8', statusDescription: 'Dr. Blade Change', group: 'ROUTINE_PROCESS', family: 'DOCTOR_BLADE_CHAMBER' },
  { eventType: 'B', statusCode: '83', statusDescription: 'Drum: Clean', group: 'ROUTINE_PROCESS', family: 'CLEANING_WASH' },
  { eventType: 'B', statusCode: '145-3', statusDescription: 'Drum Clean', group: 'ROUTINE_PROCESS', family: 'CLEANING_WASH' },
  { eventType: 'B', statusCode: '83', statusDescription: 'Drum Clean', group: 'ROUTINE_PROCESS', family: 'CLEANING_WASH' },
  { eventType: 'B', statusCode: '99', statusDescription: 'Plates: Wash', group: 'ROUTINE_PROCESS', family: 'CLEANING_WASH' },
  { eventType: 'B', statusCode: '145-4', statusDescription: 'Plate Wash', group: 'ROUTINE_PROCESS', family: 'CLEANING_WASH' },
  { eventType: 'B', statusCode: '350', statusDescription: 'Roll Change', group: 'ROUTINE_PROCESS', family: 'ROLL_MATERIAL' },
  { eventType: 'B', statusCode: '301', statusDescription: 'Cambio de Rollo', group: 'ROUTINE_PROCESS', family: 'ROLL_MATERIAL' },
  { eventType: 'B', statusCode: '318', statusDescription: 'Cambio de Rollo de Zipper', group: 'ROUTINE_PROCESS', family: 'ROLL_MATERIAL' },
  { eventType: 'B', statusCode: '354', statusDescription: 'Housekeeping', group: 'ROUTINE_PROCESS', family: 'CLEANING_WASH' },
  { eventType: 'B', statusCode: '139', statusDescription: 'Rewind Material', group: 'ROUTINE_PROCESS', family: 'ROLL_MATERIAL' },
  { eventType: 'B', statusCode: '145-5', statusDescription: 'Plate Up', group: 'ROUTINE_PROCESS', family: 'SLEEVES_PLATES' },
  { eventType: 'M', statusCode: '47-14', statusDescription: 'MR Anilox Change (Low volume)', group: 'ROUTINE_PROCESS', family: 'ANILOX' },
  { eventType: 'M', statusCode: '47-15', statusDescription: 'MR Anilox Change (High Volume)', group: 'ROUTINE_PROCESS', family: 'ANILOX' },
  { eventType: 'M', statusCode: '47-16', statusDescription: 'MR Score Line (Anilox)', group: 'ADJUSTMENT_QUALITY', family: 'ANILOX' },
  { eventType: 'M', statusCode: '47-17', statusDescription: 'Make Ready Dirty Anilox', group: 'ROUTINE_PROCESS', family: 'ANILOX' },
  { eventType: 'M', statusCode: '47-24', statusDescription: 'MR Sticky Back Change', group: 'ROUTINE_PROCESS', family: 'SLEEVES_PLATES' },
  { eventType: 'B', statusCode: 'OPDT005', statusDescription: 'Change of closure raw material', group: 'ROUTINE_PROCESS', family: 'ROLL_MATERIAL' },
  { eventType: 'M', statusCode: '47-3', statusDescription: 'Make Ready Ghosting', group: 'ADJUSTMENT_QUALITY', family: 'IMPRESSION_REGISTER_PRINT_QUALITY' },
  { eventType: 'M', statusCode: '47-4', statusDescription: 'Make Ready Bouncing', group: 'ADJUSTMENT_QUALITY', family: 'IMPRESSION_REGISTER_PRINT_QUALITY' },
  { eventType: 'M', statusCode: '47-8', statusDescription: 'Make Ready Color Match', group: 'ADJUSTMENT_QUALITY', family: 'INK_COLOR' },
  { eventType: 'M', statusCode: '50', statusDescription: 'Make Ready - Color Match', group: 'ADJUSTMENT_QUALITY', family: 'INK_COLOR' },
  { eventType: 'M', statusCode: '85', statusDescription: 'Make Ready - Color Match', group: 'ADJUSTMENT_QUALITY', family: 'INK_COLOR' },
  { eventType: 'M', statusCode: '47-20', statusDescription: 'Make Ready Out of Register', group: 'ADJUSTMENT_QUALITY', family: 'IMPRESSION_REGISTER_PRINT_QUALITY' },
  { eventType: 'M', statusCode: '47-2', statusDescription: 'Make Ready Dirty Print', group: 'ADJUSTMENT_QUALITY', family: 'IMPRESSION_REGISTER_PRINT_QUALITY' },
  { eventType: 'M', statusCode: '47-6', statusDescription: 'Make Ready Wrong Sequence', group: 'ADJUSTMENT_QUALITY', family: 'IMPRESSION_REGISTER_PRINT_QUALITY' },
  { eventType: 'M', statusCode: '47-7', statusDescription: 'Make Ready Ink Contamination', group: 'ADJUSTMENT_QUALITY', family: 'INK_COLOR' },
  { eventType: 'M', statusCode: '47-13', statusDescription: 'Make Ready Film Over Size', group: 'ADJUSTMENT_QUALITY', family: 'ROLL_MATERIAL' },
  { eventType: 'M', statusCode: '47-19', statusDescription: 'Make Ready Sleeve Low Spot', group: 'ADJUSTMENT_QUALITY', family: 'SLEEVES_PLATES' },
  { eventType: 'B', statusCode: '95', statusDescription: 'Press Problem / Impression', group: 'ADJUSTMENT_QUALITY', family: 'IMPRESSION_REGISTER_PRINT_QUALITY' },
  { eventType: 'B', statusCode: '145-2', statusDescription: 'Poor Print', group: 'ADJUSTMENT_QUALITY', family: 'IMPRESSION_REGISTER_PRINT_QUALITY' },
  { eventType: 'B', statusCode: '86', statusDescription: 'Ink: Contamination', group: 'ADJUSTMENT_QUALITY', family: 'INK_COLOR' },
  { eventType: 'B', statusCode: '87', statusDescription: 'Ink: Off Color', group: 'ADJUSTMENT_QUALITY', family: 'INK_COLOR' },
  { eventType: 'B', statusCode: '93', statusDescription: 'Plates: Defective Pre-Press', group: 'ADJUSTMENT_QUALITY', family: 'SLEEVES_PLATES' },
  { eventType: 'B', statusCode: '97', statusDescription: 'Plates: Defective Press Ops', group: 'ADJUSTMENT_QUALITY', family: 'SLEEVES_PLATES' },
  { eventType: 'B', statusCode: '450', statusDescription: 'Non Productive', group: 'WAITING_IDLE_HOLD', family: 'UNKNOWN' },
  { eventType: 'B', statusCode: '137', statusDescription: 'Customer Approval', group: 'WAITING_IDLE_HOLD', family: 'QUALITY_APPROVAL' },
  { eventType: 'B', statusCode: '145-98', statusDescription: 'Quality Hold', group: 'WAITING_IDLE_HOLD', family: 'QUALITY_APPROVAL' },
  { eventType: 'B', statusCode: '72', statusDescription: 'Operator - No Operator', group: 'WAITING_IDLE_HOLD', family: 'TRIAL_ADMINISTRATIVE' },
  { eventType: 'B', statusCode: '89', statusDescription: 'Ink: Wait On', group: 'WAITING_IDLE_HOLD', family: 'INK_COLOR' },
  { eventType: 'B', statusCode: 'OPDT012', statusDescription: 'Waiting for lead approval', group: 'WAITING_IDLE_HOLD', family: 'QUALITY_APPROVAL' },
  { eventType: 'M', statusCode: '47-12', statusDescription: 'Make Ready Wait for Film', group: 'WAITING_IDLE_HOLD', family: 'ROLL_MATERIAL' },
  { eventType: 'M', statusCode: '47-18', statusDescription: 'MR Out of Stock of Sleeves', group: 'WAITING_IDLE_HOLD', family: 'SLEEVES_PLATES' },
  { eventType: 'M', statusCode: '47-21', statusDescription: 'MR - Wait for Plates/Mounting', group: 'WAITING_IDLE_HOLD', family: 'SLEEVES_PLATES' },
  { eventType: 'M', statusCode: '47-9', statusDescription: 'Make Ready Wait for ink', group: 'WAITING_IDLE_HOLD', family: 'INK_COLOR' },
  { eventType: 'B', statusCode: '126', statusDescription: 'Substrate - Web Break', group: 'FAULT_RECOVERY', family: 'WEB_HANDLING_WEB_BREAK' },
  { eventType: 'B', statusCode: '126', statusDescription: 'Web Break', group: 'FAULT_RECOVERY', family: 'WEB_HANDLING_WEB_BREAK' },
  { eventType: 'B', statusCode: '145-7', statusDescription: 'Film Web Break', group: 'FAULT_RECOVERY', family: 'WEB_HANDLING_WEB_BREAK' },
  { eventType: 'B', statusCode: '145-6', statusDescription: 'Ink Spill', group: 'FAULT_RECOVERY', family: 'INK_COLOR' },
  { eventType: 'B', statusCode: '145-1', statusDescription: 'Film Core Waste', group: 'FAULT_RECOVERY', family: 'ROLL_MATERIAL' },
  { eventType: 'B', statusCode: '112', statusDescription: 'Substrate - Baggy Film', group: 'FAULT_RECOVERY', family: 'SUBSTRATE' },
  { eventType: 'B', statusCode: '114', statusDescription: 'Substrate - COF', group: 'FAULT_RECOVERY', family: 'SUBSTRATE' },
  { eventType: 'B', statusCode: '119', statusDescription: 'Substrate - Gauge Variation', group: 'FAULT_RECOVERY', family: 'SUBSTRATE' },
  { eventType: 'B', statusCode: '124', statusDescription: 'Substrate - Optics', group: 'FAULT_RECOVERY', family: 'SUBSTRATE' },
  { eventType: 'B', statusCode: '125', statusDescription: 'Substrate - Other', group: 'FAULT_RECOVERY', family: 'SUBSTRATE' },
  { eventType: 'B', statusCode: '133', statusDescription: 'Substrate - Wind/Edge Profile', group: 'FAULT_RECOVERY', family: 'SUBSTRATE' },
  { eventType: 'B', statusCode: '136', statusDescription: 'Substrate - Problem Other', group: 'FAULT_RECOVERY', family: 'SUBSTRATE' },
  { eventType: 'B', statusCode: '321', statusDescription: 'Desperdicio de Rollo Danado', group: 'FAULT_RECOVERY', family: 'ROLL_MATERIAL' },
  { eventType: 'B', statusCode: '326', statusDescription: 'Problemas con el  Film', group: 'FAULT_RECOVERY', family: 'SUBSTRATE' },
  { eventType: 'M', statusCode: '47-5', statusDescription: 'Make Ready Chamber Malfunction', group: 'FAULT_RECOVERY', family: 'DOCTOR_BLADE_CHAMBER' },
  { eventType: 'M', statusCode: '47-22', statusDescription: 'MR Plate Damage in Press', group: 'FAULT_RECOVERY', family: 'SLEEVES_PLATES' },
  { eventType: 'M', statusCode: '47-23', statusDescription: 'MR Plate Damage in Pre Press', group: 'FAULT_RECOVERY', family: 'SLEEVES_PLATES' },
  { eventType: 'M', statusCode: '47-25', statusDescription: 'MR Wrong Mount', group: 'FAULT_RECOVERY', family: 'SLEEVES_PLATES' },
  { eventType: 'M', statusCode: '47-26', statusDescription: 'Make Ready Wrong Plate', group: 'FAULT_RECOVERY', family: 'SLEEVES_PLATES' },
  { eventType: 'M', statusCode: '47-27', statusDescription: 'Make Ready Wrong Sleeve', group: 'FAULT_RECOVERY', family: 'SLEEVES_PLATES' },
  { eventType: 'B', statusCode: '29', statusDescription: 'Electrical: Press Other', group: 'MAINTENANCE_INTERVENTION', family: 'MECHANICAL_ELECTRICAL' },
  { eventType: 'B', statusCode: '29', statusDescription: 'Electrical Problem', group: 'MAINTENANCE_INTERVENTION', family: 'MECHANICAL_ELECTRICAL' },
  { eventType: 'B', statusCode: '35', statusDescription: 'Electrical - Press: Print Deck', group: 'MAINTENANCE_INTERVENTION', family: 'MECHANICAL_ELECTRICAL' },
  { eventType: 'B', statusCode: '64', statusDescription: 'Mech - Press Other', group: 'MAINTENANCE_INTERVENTION', family: 'MECHANICAL_ELECTRICAL' },
  { eventType: 'B', statusCode: '64', statusDescription: 'Mechanical Problem', group: 'MAINTENANCE_INTERVENTION', family: 'MECHANICAL_ELECTRICAL' },
  { eventType: 'B', statusCode: '68', statusDescription: 'Mech - Press: Printing Deck', group: 'MAINTENANCE_INTERVENTION', family: 'MECHANICAL_ELECTRICAL' },
  { eventType: 'B', statusCode: '88', statusDescription: 'Pump Problem', group: 'MAINTENANCE_INTERVENTION', family: 'MECHANICAL_ELECTRICAL' },
  { eventType: 'B', statusCode: '308', statusDescription: 'Falla Mechanica', group: 'MAINTENANCE_INTERVENTION', family: 'MECHANICAL_ELECTRICAL' },
  { eventType: 'B', statusCode: '351', statusDescription: 'Falla electrica', group: 'MAINTENANCE_INTERVENTION', family: 'MECHANICAL_ELECTRICAL' },
  { eventType: 'B', statusCode: '41-1', statusDescription: 'Maintenance - Mechanical', group: 'MAINTENANCE_INTERVENTION', family: 'MAINTENANCE' },
  { eventType: 'B', statusCode: '41-2', statusDescription: 'Maintenance - Electrical', group: 'MAINTENANCE_INTERVENTION', family: 'MAINTENANCE' },
  { eventType: 'B', statusCode: '41-3', statusDescription: 'Maintenance - Pump', group: 'MAINTENANCE_INTERVENTION', family: 'MAINTENANCE' },
  { eventType: 'B', statusCode: '41-4', statusDescription: 'Maintenance - Dryer', group: 'MAINTENANCE_INTERVENTION', family: 'MAINTENANCE' },
  { eventType: 'B', statusCode: '41-5', statusDescription: 'Maintenance - CI Section', group: 'MAINTENANCE_INTERVENTION', family: 'MAINTENANCE' },
  { eventType: 'B', statusCode: '15', statusDescription: 'Computer/Radius/IT', group: 'ADMIN_UNKNOWN', family: 'TRIAL_ADMINISTRATIVE' },
  { eventType: 'B', statusCode: '138', statusDescription: 'RD Trial', group: 'ADMIN_UNKNOWN', family: 'TRIAL_ADMINISTRATIVE' },
  { eventType: 'B', statusCode: '378', statusDescription: 'Cambio de Turno', group: 'ADMIN_UNKNOWN', family: 'TRIAL_ADMINISTRATIVE' },
  { eventType: 'B', statusCode: '145-99', statusDescription: 'Other', group: 'ADMIN_UNKNOWN', family: 'UNKNOWN', confidence: 'LOW', review: true },
  { eventType: 'H', statusCode: null, statusDescription: '', group: 'ADMIN_UNKNOWN', family: 'UNKNOWN', confidence: 'LOW', review: true },
  { eventType: 'S', statusCode: '400', statusDescription: 'Sort', group: 'ADMIN_UNKNOWN', family: 'TRIAL_ADMINISTRATIVE', confidence: 'LOW', review: true },
  { eventType: 'M', statusCode: '021', statusDescription: 'Planning Error', group: 'ADMIN_UNKNOWN', family: 'TRIAL_ADMINISTRATIVE', confidence: 'LOW', review: true },
  { eventType: 'M', statusCode: '47-99', statusDescription: 'Make Ready Other', group: 'ADMIN_UNKNOWN', family: 'MAKE_READY', confidence: 'LOW', review: true },
  { eventType: 'B', statusCode: '102', statusDescription: 'Poor Print (Obsolete)', group: 'ADMIN_UNKNOWN', family: 'IMPRESSION_REGISTER_PRINT_QUALITY', obsolete: true, review: true },
  { eventType: 'B', statusCode: '106', statusDescription: 'Quality Hold (Obsolete)', group: 'ADMIN_UNKNOWN', family: 'QUALITY_APPROVAL', obsolete: true, review: true },
  { eventType: 'B', statusCode: '128', statusDescription: 'Core Waste (Obsolete)', group: 'ADMIN_UNKNOWN', family: 'ROLL_MATERIAL', obsolete: true, review: true },
  { eventType: 'B', statusCode: '94', statusDescription: 'Plates: Plate Up (Obsolete)', group: 'ADMIN_UNKNOWN', family: 'SLEEVES_PLATES', obsolete: true, review: true },
]

export const SEEDED_CLASSIFICATIONS: RadiusStateClassification[] = seeds.map((seed) => {
  const operationalGroup = groupByKey.get(seed.group)!
  const processFamily = familyByKey.get(seed.family)!
  return {
    identity: exactRadiusIdentity(seed), eventType: seed.eventType, statusCode: seed.statusCode, statusDescription: seed.statusDescription,
    operationalGroupId: operationalGroup.id, operationalGroupKey: operationalGroup.key,
    processFamilyId: processFamily.id, processFamilyKey: processFamily.key,
    displayLabel: null, explanation: 'Seeded from the verified Radius catalog and conservative operational semantics.',
    confidence: seed.confidence ?? 'HIGH', needsReview: seed.review ?? false,
    defaultTimelineVisibility: true, obsolete: seed.obsolete ?? false,
  }
})

export function seededSnapshot(): ClassificationSnapshot {
  return { version: 1, publishedAtUtc: null, publishedBy: null, groups: structuredClone(SEEDED_OPERATIONAL_GROUPS), families: structuredClone(SEEDED_PROCESS_FAMILIES), classifications: structuredClone(SEEDED_CLASSIFICATIONS) }
}
