import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import type { AddressInfo } from 'node:net'
import { readFileSync } from 'node:fs'
import { createApp } from '../src/app.js'
import type { RadiusPressKey, RadiusStatusSegment } from '../src/radius/models.js'
import type { RadiusService } from '../src/radius/radius-service.js'
import type { ProductionContextEvidence, TelemetrySample } from '../src/telemetry/telemetry-contracts.js'
import type { TelemetryFoundationService } from '../src/telemetry/telemetry-foundation-service.js'
import type { TelemetryClient } from '../src/telemetry/telemetry-api-client.js'
import { CHANGEOVER_CONFIRMATION_SECONDS_DEFAULT, CHANGEOVER_RECOVERY_SPEED_DEFAULT, CHANGEOVER_STOP_SPEED_DEFAULT, type ChangeoverDefinition } from '../src/changeover-intelligence/contracts.js'
import { assembleChangeovers, detectPhysicalStops, distribution, reconcileRadius, resolveOrderTransitions, summarizeDaily, summarizeRecoveryCohorts, summarizeSequences, summarizeTransitionPairs } from '../src/changeover-intelligence/engine.js'
import { ChangeoverIntelligenceService } from '../src/changeover-intelligence/service.js'
import { ChangeoverRadiusAcquisitionGuard } from '../src/changeover-intelligence/radius-acquisition-guard.js'

const origin = '2026-08-01T00:00:00.000Z'
const at = (minutes: number) => new Date(Date.parse(origin) + minutes * 60_000).toISOString()
const rule: ChangeoverDefinition = { stopSpeed: CHANGEOVER_STOP_SPEED_DEFAULT, recoverySpeed: CHANGEOVER_RECOVERY_SPEED_DEFAULT, recoveryConfirmationSeconds: CHANGEOVER_CONFIRMATION_SECONDS_DEFAULT, source: 'DEFAULT', stopRule: 'speed_below_threshold_debounced', recoveryRule: 'first_speed_above_threshold_sustained', identityRule: 'resolved_order_changed' }
function sample(minutes: number, value: number): TelemetrySample { return { observedAtUtc: at(minutes), receivedAtUtc: at(minutes), sourceTimestampUtc: at(minutes), qualityState: 'good', valueKind: 'numeric', value } }
function samples(values: Array<[number, number]>) { return values.map(([minute, value]) => sample(minute, value)) }
function field(name: 'job' | 'order' | 'recipe' | 'customer' | 'material' | 'roll', value: string | null) { return { field: name, canonicalId: `production.${name}`, capabilityState: 'SUPPORTED' as const, observationState: value ? 'SUPPORTED_WITH_SEED_ONLY' as const : 'SUPPORTED_WITH_NO_SAMPLES_IN_RANGE' as const, seed: value ? { observedAtUtc: at(-1), receivedAtUtc: at(-1), sourceTimestampUtc: at(-1), qualityState: 'good', valueKind: 'string' as const, value } : null, changes: [] } }
function context(changes: Array<[number, string]>, toMinute = 30, order: string | null = 'A'): ProductionContextEvidence { return { pressKey: 'press5', sourceKey: 'press5', displayName: 'Press 5', fromUtc: at(0), toUtc: at(toMinute), fields: { job: field('job', null), order: field('order', order), recipe: field('recipe', null), customer: field('customer', null), material: field('material', null), roll: field('roll', null) }, changes: changes.map(([minute, value]) => ({ atUtc: at(minute), field: 'order', canonicalId: 'production.order', previousValueKind: 'string', previousValue: order ?? '', valueKind: 'string', value, qualityState: 'good' })) } }
function radius(start: number, end: number, eventType: string, statusCode: string, description: string, isProduction = false, group?: string, family: 'MAKE_READY' | 'CLEANING_WASH' | 'IMPRESSION_REGISTER_PRINT_QUALITY' = 'MAKE_READY'): RadiusStatusSegment { return { kind: 'radius', machineId: 1, pressKey: 'press5', displayName: 'Press 5', startUtc: at(start), endUtc: at(end), durationSeconds: (end - start) * 60, isOpen: false, sourceGeneration: 'compact', eventType, statusCode, statusDescription: description, isProduction, ...(group ? { classification: { identity: `${eventType}|${statusCode}|${description}`, eventType, statusCode, statusDescription: description, operationalGroupId: group, operationalGroupKey: group as never, processFamilyId: family, processFamilyKey: family, displayLabel: null, explanation: 'fixture', confidence: 'HIGH', needsReview: false, defaultTimelineVisibility: true, obsolete: false, operationalGroupName: group.replaceAll('_', ' '), operationalGroupDescription: '', operationalGroupLightColor: '', operationalGroupDarkColor: '', operationalGroupIcon: '', processFamilyName: family.replaceAll('_', ' '), mappingVersion: 1, isFallback: false } } : {}) } }
function offline(start: number, end: number): RadiusStatusSegment { return { kind: 'offline', machineId: 1, pressKey: 'press5', displayName: 'Press 5', startUtc: at(start), endUtc: at(end), durationSeconds: (end - start) * 60, isOpen: false, sourceGeneration: 'offline_inference', eventType: null, statusCode: null, statusDescription: null, isProduction: false } }
const standardSpeed = () => samples([[0, 800], [1, 0], [2, 0], [3, 0], [4, 600], [5, 700], [6, 700], [7, 700], [8, 700], [9, 700]])
function telemetryFixture(): TelemetryFoundationService {
  return { semanticHistory: async (pressKey: RadiusPressKey) => ({ pressKey, sourceKey: pressKey, displayName: pressKey, fromUtc: at(0), toUtc: at(30), includeSeed: true, signals: [{ canonicalId: 'machine.speed.actual', deckNumber: null, capabilityState: 'SUPPORTED', observationState: 'SUPPORTED_WITH_OBSERVATIONS', sourceUnit: 'fpm', canonicalUnitStatus: 'canonical', seed: null, samples: standardSpeed(), changes: [], representation: 'samples' }, { canonicalId: 'production.order', deckNumber: null, capabilityState: 'SUPPORTED', observationState: 'SUPPORTED_WITH_OBSERVATIONS', sourceUnit: null, canonicalUnitStatus: 'not_applicable', seed: { observedAtUtc: at(-1), receivedAtUtc: at(-1), sourceTimestampUtc: at(-1), qualityState: 'good', valueKind: 'string', value: 'A' }, samples: [], changes: [{ observedAtUtc: at(2), receivedAtUtc: at(2), sourceTimestampUtc: at(2), qualityState: 'good', valueKind: 'string', value: 'B', previousObservedAtUtc: at(-1), previousReceivedAtUtc: at(-1), previousSourceTimestampUtc: at(-1), previousQualityState: 'good', previousValueKind: 'string', previousValue: 'A' }], representation: 'changes' }], readDiagnostics: {} }) } as unknown as TelemetryFoundationService
}
function stoppedUntil(recoveryMinute: number) { return samples([[0, 800], ...Array.from({ length: recoveryMinute - 1 }, (_, index) => [index + 1, 0] as [number, number]), ...Array.from({ length: 6 }, (_, index) => [recoveryMinute + index, 700] as [number, number])]) }

describe('Changeover Intelligence deterministic fixtures A-K', () => {
  it('A: uses first stopped sample and first sustained recovery sample as physical bounds', () => { const stops = detectPhysicalStops(standardSpeed(), rule); assert.equal(stops.length, 1); assert.equal(stops[0]!.physicalStartUtc, at(1)); assert.equal(stops[0]!.stopConfirmedAtUtc, at(2)); assert.equal(stops[0]!.physicalRecoveryUtc, at(4)); assert.equal(stops[0]!.recoveryConfirmedAtUtc, at(9)); assert.equal(stops[0]!.durationSeconds, 180) })
  it('B: treats exact stop and recovery threshold values as non-qualifying', () => { const stops = detectPhysicalStops(samples([[0, 800], [1, 1], [2, 1], [3, 0], [4, 0], [5, 500], [6, 501], [7, 501], [8, 501], [9, 501], [10, 501], [11, 501]]), rule); assert.equal(stops[0]!.physicalStartUtc, at(3)); assert.equal(stops[0]!.physicalRecoveryUtc, at(6)) })
  it('C: debounces a single below-threshold sample', () => { assert.deepEqual(detectPhysicalStops(samples([[0, 800], [1, 0], [2, 800], [3, 800]]), rule), []) })
  it('D: records failed recovery attempts and still confirms a later recovery', () => { const stops = detectPhysicalStops(samples([[0, 800], [1, 0], [2, 0], [3, 0], [4, 600], [5, 600], [6, 400], [7, 700], [8, 700], [9, 700], [10, 700], [11, 700], [12, 700]]), rule); assert.equal(stops[0]!.physicalRecoveryUtc, at(7)); assert.deepEqual(stops[0]!.failedRecoveryAttempts, [{ candidateStartUtc: at(4), endedAtUtc: at(6), durationSeconds: 120, outcome: 'FAILED', failureReason: 'speed_at_or_below_threshold' }]) })
  it('E: does not bridge a telemetry gap', () => { const stops = detectPhysicalStops(samples([[0, 800], [1, 0], [2, 0], [12, 700], [13, 700]]), rule); assert.equal(stops[0]!.evidenceState, 'INTERRUPTED'); assert.equal(stops[0]!.physicalRecoveryUtc, null); assert.equal(stops[0]!.telemetryGap?.durationSeconds, 600) })
  it('F: classifies the same stable Order as another stop', () => { const stops = detectPhysicalStops(standardSpeed(), rule); const result = assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([]), stops }); assert.equal(result.events[0]!.classification, 'OTHER_STOP') })
  it('G: distinguishes missing and conflicting Order evidence from a confirmed changeover', () => { const missing = assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([], 30, null), stops: detectPhysicalStops(standardSpeed(), rule) }); assert.equal(missing.events[0]!.classification, 'AMBIGUOUS_STOP'); const longStop = detectPhysicalStops(samples([[0, 800], ...Array.from({ length: 19 }, (_, index) => [index + 1, 0] as [number, number]), [20, 600], [21, 600], [22, 600], [23, 600], [24, 600], [25, 600]]), rule); const conflicting = assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([[2, 'B'], [10, 'C']], 30), stops: longStop }); assert.equal(conflicting.events[0]!.orderTransition.settleState, 'CONFLICTING'); assert.equal(conflicting.events[0]!.classification, 'AMBIGUOUS_STOP') })
  it('H: tracks a settled metadata-only Order transition separately', () => { const result = assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([[15, 'B']], 30), stops: detectPhysicalStops(standardSpeed(), rule) }); assert.equal(result.metadataOnlyTransitions.length, 1); assert.equal(result.events[0]!.classification, 'OTHER_STOP') })
  it('I: preserves Radius production recorded inside the physical stop as a mismatch', () => { const physical = detectPhysicalStops(standardSpeed(), rule)[0]!; const result = reconcileRadius(physical, [radius(0, 2, 'G', '10', 'Run Production', true), radius(2, 4, 'M', '20', 'Setup', false, 'make_ready'), radius(4, 10, 'G', '10', 'Run Production', true)])!; assert.equal(result.adjustedContributions[0]!.phase, 'RADIUS_PRODUCTION_MISMATCH'); assert.equal(result.differenceSeconds, 0) })
  it('J: clips raw Radius intervals, fills gaps, and reconciles exactly', () => { const physical = { ...detectPhysicalStops(standardSpeed(), rule)[0]!, physicalRecoveryUtc: at(5), durationSeconds: 240 }; const result = reconcileRadius(physical, [radius(0, 2, 'G', '10', 'Run Production', true), radius(2, 3, 'M', '20', 'Setup'), offline(3, 4), radius(4, 4.5, 'B', '30', 'Breakdown'), radius(4.5, 6, 'G', '10', 'Run Production', true)])!; assert.equal(result.rawIntervals[0]!.originalStartUtc, at(0)); assert.equal(result.rawIntervals[0]!.originalDurationSeconds, 120); assert.deepEqual(result.adjustedContributions.map((item) => item.durationSeconds), [60, 60, 60, 30, 30]); assert.equal(result.adjustedDurationSeconds, 240); assert.equal(result.differenceSeconds, 0); assert.equal(result.annotationStartLagSeconds, 60); assert.equal(result.annotationEndLagSeconds, -30) })
  it('K: retains zero-event days and applies support-aware aggregation', () => { const stops = detectPhysicalStops(standardSpeed(), rule); const assembled = assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([[2, 'B']]), stops, radiusSegments: [radius(0, 4, 'M', '20', 'Setup')] }); const events = assembled.events.filter((item) => item.classification === 'CONFIRMED_CHANGEOVER'); assert.equal(events.length, 1); assert.deepEqual(summarizeDaily(events, at(0), at(3 * 24 * 60)).map((item) => item.count), [1, 0, 0, 0]); const pair = summarizeTransitionPairs(events)[0]!; assert.equal(pair.support.level, 'insufficient'); assert.deepEqual(pair.presses, ['press5']); assert.deepEqual(pair.dominantSequence, ['MAKE_READY']); assert.equal(pair.failedRecoveryPercent, 0); assert.equal(summarizeSequences(events)[0]!.count, 1); assert.deepEqual(summarizeRecoveryCohorts(events).map((item) => [item.attemptBand, item.changeoverCount]), [['0', 1], ['1', 0], ['multiple', 0]]); assert.equal(distribution([1, 2, 3, 4]).median, 2.5) })
})

describe('Changeover Intelligence edge semantics', () => {
  it('includes definition thresholds in deterministic event identity', () => { const stops = detectPhysicalStops(standardSpeed(), rule); const base = assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([[2, 'B']]), stops, definition: rule }).events[0]!; const custom = assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([[2, 'B']]), stops, definition: { ...rule, stopSpeed: .5, source: 'CUSTOM' } }).events[0]!; assert.notEqual(base.changeoverId, custom.changeoverId); assert.equal(base.changeoverId, assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([[2, 'B']]), stops, definition: rule }).events[0]!.changeoverId) })
  it('invalidates a recovery candidate at a telemetry gap and releases a later independent stop', () => { const stops = detectPhysicalStops(samples([[0, 800], [1, 0], [2, 0], [3, 600], [10, 0], [11, 0], [12, 700], [13, 700], [14, 700], [15, 700], [16, 700], [17, 700]]), rule); assert.equal(stops[0]!.evidenceState, 'INTERRUPTED'); assert.equal(stops[0]!.failedRecoveryAttempts[0]!.failureReason, 'telemetry_gap'); assert.equal(stops[1]!.physicalRecoveryUtc, at(12)) })
  it('coalesces asynchronous usable Order values and ignores blank propagation', () => { const fixture = context([[2, 'B'], [3, ''], [4, 'C']], 20); const transitions = resolveOrderTransitions(fixture); assert.equal(transitions.length, 1); assert.equal(transitions[0]!.identityChangeFirstSeenAtUtc, at(2)); assert.equal(transitions[0]!.identityLastChangeAtUtc, at(4)); assert.equal(transitions[0]!.identitySettledAtUtc, at(9)); assert.equal(transitions[0]!.finalResolvedOrder, 'C'); assert.deepEqual(transitions[0]!.intermediateValues, ['B', 'C']) })
  it('compresses consecutive phases for patterns, retains loops, and preserves unknown exact identity', () => { const physical = { ...detectPhysicalStops(standardSpeed(), rule)[0]!, physicalRecoveryUtc: at(5), durationSeconds: 240 }; const assembled = assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([[2, 'B']]), stops: [physical], radiusSegments: [radius(1, 2, 'M', '20', 'Setup A'), radius(2, 3, 'M', '21', 'Setup B'), radius(3, 4, 'B', 'X9', 'Unmapped exact reason'), radius(4, 5, 'M', '22', 'Setup C')] }); const event = assembled.events[0]!; assert.deepEqual(event.phaseSequence, ['MAKE_READY', 'BREAKDOWN', 'MAKE_READY']); assert.equal(summarizeSequences([event])[0]!.loopCount, 1); assert.deepEqual(event.exactRadiusSequence[2], { eventType: 'B', statusCode: 'X9', statusDescription: 'Unmapped exact reason' }) })
  it('marks Radius gaps as insufficient evidence without changing physical bounds', () => { const physical = { ...detectPhysicalStops(standardSpeed(), rule)[0]!, physicalRecoveryUtc: at(5), durationSeconds: 240 }; const event = assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([[2, 'B']]), stops: [physical], radiusSegments: [radius(1, 3, 'M', '20', 'Setup'), offline(3, 4), radius(4, 5, 'M', '21', 'Setup')] }).events[0]!; assert.equal(event.evidenceState, 'INSUFFICIENT_EVIDENCE'); assert.equal(event.physical.physicalRecoveryUtc, at(5)); assert.equal(event.radius?.differenceSeconds, 0) })
})

describe('representative plant-behavior fixtures A-K', () => {
  it('Fixture A — normal clean changeover', () => { const event = assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([[2, 'B']]), stops: detectPhysicalStops(standardSpeed(), rule), radiusSegments: [radius(1, 4, 'M', '20', 'Setup', false, 'make_ready')], definition: rule }).events[0]!; assert.equal(event.classification, 'CONFIRMED_CHANGEOVER'); assert.equal(event.physical.durationSeconds, 180) })
  it('Fixture B — long setup', () => { const event = assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([[2, 'B']], 40), stops: detectPhysicalStops(stoppedUntil(20), rule), radiusSegments: [radius(1, 20, 'M', '20', 'Long setup', false, 'make_ready')], definition: rule }).events[0]!; assert.equal(event.physical.durationSeconds, 1_140); assert.deepEqual(event.phaseSequence, ['MAKE_READY']) })
  it('Fixture C — cleaning/registration loop', () => { const event = assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([[2, 'B']]), stops: [{ ...detectPhysicalStops(standardSpeed(), rule)[0]!, physicalRecoveryUtc: at(5), durationSeconds: 240 }], radiusSegments: [radius(1, 2, 'M', '40', 'Cleaning', false, 'changeover_setup', 'CLEANING_WASH'), radius(2, 3, 'M', '41', 'Registration', false, 'changeover_setup', 'IMPRESSION_REGISTER_PRINT_QUALITY'), radius(3, 5, 'M', '40', 'Cleaning', false, 'changeover_setup', 'CLEANING_WASH')], definition: rule }).events[0]!; assert.deepEqual(event.phaseSequence, ['CLEANING_WASH', 'REGISTRATION_QUALITY', 'CLEANING_WASH']); assert.equal(summarizeSequences([event])[0]!.loopCount, 1) })
  it('Fixture D — failed recovery attempt', () => { const event = assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([[2, 'B']]), stops: detectPhysicalStops(samples([[0, 800], [1, 0], [2, 0], [3, 600], [4, 300], [5, 700], [6, 700], [7, 700], [8, 700], [9, 700], [10, 700]]), rule), definition: rule }).events[0]!; assert.equal(event.physical.failedRecoveryAttempts.length, 1) })
  it('Fixture E — Radius annotation begins late', () => { const event = assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([[2, 'B']]), stops: detectPhysicalStops(standardSpeed(), rule), radiusSegments: [radius(0, 2, 'G', '10', 'Run Production', true), radius(2, 4, 'M', '20', 'Setup')], definition: rule }).events[0]!; assert.equal(event.radius?.annotationStartLagSeconds, 60); assert.equal(event.radius?.adjustedContributions[0]!.phase, 'RADIUS_PRODUCTION_MISMATCH') })
  it('Fixture F — Radius returns production before physical recovery', () => { const physical = { ...detectPhysicalStops(standardSpeed(), rule)[0]!, physicalRecoveryUtc: at(5), durationSeconds: 240 }; const event = assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([[2, 'B']]), stops: [physical], radiusSegments: [radius(1, 4.5, 'M', '20', 'Setup'), radius(4.5, 6, 'G', '10', 'Run Production', true)], definition: rule }).events[0]!; assert.equal(event.radius?.annotationEndLagSeconds, -30); assert.equal(event.physical.physicalRecoveryUtc, at(5)) })
  it('Fixture G — same-Order physical stop', () => { assert.equal(assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([]), stops: detectPhysicalStops(standardSpeed(), rule), definition: rule }).events[0]!.classification, 'OTHER_STOP') })
  it('Fixture H — ambiguous missing Order', () => { assert.equal(assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([], 30, null), stops: detectPhysicalStops(standardSpeed(), rule), definition: rule }).events[0]!.classification, 'AMBIGUOUS_STOP') })
  it('Fixture I — telemetry gap', () => { assert.equal(detectPhysicalStops(samples([[0, 800], [1, 0], [2, 0], [12, 700]]), rule)[0]!.evidenceState, 'INTERRUPTED') })
  it('Fixture J — zero-changeover day', () => { assert.deepEqual(summarizeDaily([], at(0), at(24 * 60)).map((day) => day.count), [0, 0]) })
  it('Fixture K — same Order pair on presses with different physical performance', () => { const fast = assembleChangeovers({ pressKey: 'press5', displayName: 'Press 5', context: context([[2, 'B']]), stops: detectPhysicalStops(standardSpeed(), rule), definition: rule }).events[0]!; const slow = assembleChangeovers({ pressKey: 'press8', displayName: 'Press 8', context: context([[2, 'B']], 40), stops: detectPhysicalStops(stoppedUntil(20), rule), definition: rule }).events[0]!; const pair = summarizeTransitionPairs([fast, slow])[0]!; assert.deepEqual(pair.presses, ['press5', 'press8']); assert.equal(pair.duration.median, 660) })
})

describe('Changeover Intelligence shared service safety', () => {
  it('coalesces equivalent fleet reports and keeps all 12 Radius acquisitions sequential', async () => {
    let active = 0; let peak = 0; let acquisitions = 0
    const telemetry = telemetryFixture()
    const radiusService = { getRawTimeline: async (pressKey: RadiusPressKey) => { active += 1; peak = Math.max(peak, active); acquisitions += 1; await new Promise((resolve) => setTimeout(resolve, 2)); active -= 1; return { pressKey, displayName: pressKey, fromUtc: at(0), toUtc: at(30), segments: [radius(0, 30, 'M', '20', 'Setup')] } } } as unknown as RadiusService
    const service = new ChangeoverIntelligenceService(radiusService, telemetry, () => new Date(at(30))); const input = { fromUtc: at(0), toUtc: at(30), mode: 'CHANGEOVERS' as const, focusPressKey: null, stopSpeed: 1, recoverySpeed: 500, recoveryConfirmationSeconds: 300 }
    const [first, second] = await Promise.all([service.report(input), service.report({ ...input, focusPressKey: 'press5' })])
    const contextual = await service.report({ ...input, mode: 'ALL_STOPS' })
    assert.equal(acquisitions, 12); assert.equal(peak, 1); assert.equal(first.diagnostics.sequentialRadiusAcquisitions, 12); assert.equal(first.diagnostics.radiusConcurrencyCap, 1); assert.equal(first.diagnostics.peakConcurrentRadiusAcquisitions, 1); assert.equal(first.diagnostics.radiusQueuedAtCompletion, 0); assert.equal(first.fleet.length, 12); assert.equal(first.fleet[0]!.duration.p90, 180); assert.equal(first.fleet[0]!.failedRecoveriesPerChangeover, 0); assert.equal(second.diagnostics.cache, 'SHARED'); assert.equal(second.fleet.find((item) => item.pressKey === 'press5')?.focused, true); assert.equal(second.fleet.filter((item) => !item.focused).length, 11); assert.equal(contextual.diagnostics.cache, 'HIT')
  })

  it('isolates Radius failure as PARTIAL and a cancelled consumer does not poison the queue', async () => {
    let acquisitions = 0
    const telemetry = telemetryFixture()
    const radiusService = { getRawTimeline: async () => { acquisitions += 1; await new Promise((resolve) => setTimeout(resolve, 1)); throw new Error('fixture unavailable') } } as unknown as RadiusService
    const service = new ChangeoverIntelligenceService(radiusService, telemetry); const input = { fromUtc: at(0), toUtc: at(30), mode: 'CHANGEOVERS' as const, focusPressKey: null, stopSpeed: 1, recoverySpeed: 500, recoveryConfirmationSeconds: 300 }; const controller = new AbortController(); const cancelled = service.report(input, 'cancelled', controller.signal); const survivor = service.report(input, 'survivor'); controller.abort()
    await assert.rejects(cancelled, { name: 'AbortError' }); const report = await survivor; assert.equal(report.evidenceState, 'PARTIAL'); assert.equal(report.changeovers.length, 12); assert.equal(acquisitions, 12); assert.equal(report.changeovers.every((event) => event.radius === null), true)
  })
})

describe('Changeover Radius acquisition guard', () => {
  it('runs FIFO at cap one and releases permits after cancellation and errors without deadlock', async () => {
    const guard = new ChangeoverRadiusAcquisitionGuard(1); const order: string[] = []; let releaseFirst!: () => void
    const firstGate = new Promise<void>((resolve) => { releaseFirst = resolve })
    const first = guard.run(async () => { order.push('first'); await firstGate })
    await new Promise((resolve) => setTimeout(resolve, 0))
    const cancelledController = new AbortController(); const cancelled = guard.run(async () => { order.push('cancelled') }, { signal: cancelledController.signal })
    const failed = guard.run(async () => { order.push('failed'); throw new Error('expected fixture failure') })
    const survivor = guard.run(async () => { order.push('survivor'); return 'done' })
    assert.deepEqual(guard.diagnostics(), { cap: 1, active: 1, queued: 3, lifetimePeak: 1 })
    cancelledController.abort(); await assert.rejects(cancelled, { name: 'AbortError' }); assert.equal(guard.diagnostics().queued, 2)
    releaseFirst(); await first; await assert.rejects(failed, /expected fixture failure/); assert.equal(await survivor, 'done')
    assert.deepEqual(order, ['first', 'failed', 'survivor']); assert.deepEqual(guard.diagnostics(), { cap: 1, active: 0, queued: 0, lifetimePeak: 1 })
  })
})

describe('Changeover Intelligence HTTP validation', () => {
  it('rejects an invalid mode and unsafe threshold relationship before source access', async () => {
    const app = createApp({ telemetryClient: {} as TelemetryClient, logger: false }); const server = app.listen(0, '127.0.0.1'); await new Promise<void>((resolve) => server.once('listening', resolve)); const port = (server.address() as AddressInfo).port
    try {
      const mode = await fetch(`http://127.0.0.1:${port}/api/changeover-intelligence/report?fromUtc=${encodeURIComponent(at(0))}&toUtc=${encodeURIComponent(at(30))}&mode=AI`); assert.equal(mode.status, 400); assert.deepEqual(await mode.json(), { error: 'invalid_changeover_mode' })
      const thresholds = await fetch(`http://127.0.0.1:${port}/api/changeover-intelligence/report?fromUtc=${encodeURIComponent(at(0))}&toUtc=${encodeURIComponent(at(30))}&stopSpeed=10&recoverySpeed=5`); assert.equal(thresholds.status, 400); assert.deepEqual(await thresholds.json(), { error: 'invalid_changeover_thresholds' })
    } finally { await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())) }
  })
})

describe('Changeover Intelligence source architecture', () => {
  it('uses only the two canonical signals, the shared gap and Changeover guard, and no pool, writer, materializer, or persistence', () => { const source = readFileSync(new URL('../src/changeover-intelligence/service.ts', import.meta.url), 'utf8'); const guard = readFileSync(new URL('../src/changeover-intelligence/radius-acquisition-guard.ts', import.meta.url), 'utf8'); const engine = readFileSync(new URL('../src/changeover-intelligence/engine.ts', import.meta.url), 'utf8'); assert.match(source, /machine\.speed\.actual/); assert.match(source, /production\.order/); assert.match(source, /semanticHistory/); assert.match(source, /changeoverRadiusAcquisitionGuard/); assert.match(guard, /new ChangeoverRadiusAcquisitionGuard\(1\)/); assert.match(engine, /significantGapMs/); for (const forbidden of [/new Pool/, /from 'pg'/, /INSERT\s+INTO/i, /UPDATE\s+\w+\s+SET/i, /DELETE\s+FROM/i, /materializ/i, /backfill/i]) { assert.doesNotMatch(source, forbidden); assert.doesNotMatch(guard, forbidden) } })
})
