import { createHash } from 'node:crypto'
import type { RadiusPressKey } from '../radius/models.js'
import { isGoodTelemetryQuality } from '../telemetry/historical-telemetry-policy.js'
import { detectDeltaEvents, detectThresholdEvents, detectValueChangeEvents, type ThresholdDetection } from '../telemetry-event-explorer/telemetry-event-engine.js'
import type { IndustrialAnalyticalObservation, IndustrialBaselineMetricInput, IndustrialNumericSample, IndustrialNumericStats, IndustrialRelationshipResult, IndustrialStateSample } from './contracts.js'

export const INDUSTRIAL_ANALYTICS_RULES = {
  minimumBaselineCoveragePercent: 80,
  minimumNumericSamples: 5,
  minimumWindowSamples: 3,
  minimumRelationshipPairs: 8,
  minimumCrossPressSeries: 2,
  minimumVariance: 1e-9,
  eventContextMinutes: 20,
  maximumLagMinutes: 10,
  lagStepMinutes: 1,
  alignmentToleranceMs: 45_000,
  minimumRelationshipPairCoveragePercent: 30,
  minimumRelationshipTemporalCoveragePercent: 30,
} as const

function round(value: number, digits = 3): number { const factor = 10 ** digits; return Math.round(value * factor) / factor }
function median(values: number[]): number { const sorted = [...values].sort((a, b) => a - b); const middle = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[middle]! : (sorted[middle - 1]! + sorted[middle]!) / 2 }
function mean(values: number[]): number { return values.reduce((sum, value) => sum + value, 0) / values.length }
function deviation(values: number[]): number { const average = mean(values); return Math.sqrt(mean(values.map((value) => (value - average) ** 2))) }
function usableQuality(qualityState?: string): boolean { return qualityState === undefined || isGoodTelemetryQuality(qualityState) }
function observationId(parts: unknown[]): string { return `industrial.${createHash('sha256').update(JSON.stringify(parts)).digest('hex').slice(0, 14)}` }
function validRange(range: { start: string; end: string }): boolean { return Number.isFinite(Date.parse(range.start)) && Number.isFinite(Date.parse(range.end)) && Date.parse(range.end) > Date.parse(range.start) }
function numericSamples(input: IndustrialNumericSample[], range?: { start: string; end: string }): IndustrialNumericSample[] {
  const from = range ? Date.parse(range.start) : -Infinity; const to = range ? Date.parse(range.end) : Infinity
  const values = input.filter((item) => Number.isFinite(Date.parse(item.atUtc)) && Number.isFinite(item.value) && usableQuality(item.qualityState) && Date.parse(item.atUtc) >= from && Date.parse(item.atUtc) <= to).sort((a, b) => Date.parse(a.atUtc) - Date.parse(b.atUtc))
  const unique = new Map<number, IndustrialNumericSample>(); for (const value of values) unique.set(Date.parse(value.atUtc), value)
  return [...unique.values()]
}
function spanCoverage(samples: IndustrialNumericSample[], range: { start: string; end: string }): number {
  if (samples.length < 2 || !validRange(range)) return 0
  return round(Math.min(100, Math.max(0, (Date.parse(samples.at(-1)!.atUtc) - Date.parse(samples[0]!.atUtc)) / (Date.parse(range.end) - Date.parse(range.start)) * 100)), 1)
}

export function describeIndustrialNumeric(input: IndustrialNumericSample[]): IndustrialNumericStats | null {
  const samples = numericSamples(input); if (!samples.length) return null
  const values = samples.map(({ value }) => value); const deltas = values.slice(1).map((value, index) => value - values[index]!)
  const x = samples.map(({ atUtc }) => (Date.parse(atUtc) - Date.parse(samples[0]!.atUtc)) / 60_000); const xMean = mean(x); const yMean = mean(values)
  const denominator = x.reduce((sum, value) => sum + (value - xMean) ** 2, 0); const slope = denominator > 0 ? x.reduce((sum, value, index) => sum + (value - xMean) * (values[index]! - yMean), 0) / denominator : 0
  const valueMedian = median(values); const mad = values.length >= INDUSTRIAL_ANALYTICS_RULES.minimumNumericSamples ? median(values.map((value) => Math.abs(value - valueMedian))) : null
  const largestDelta = deltas.length ? deltas.reduce((best, value) => Math.abs(value) > Math.abs(best) ? value : best, deltas[0]!) : 0
  return { count: values.length, minimum: round(Math.min(...values)), maximum: round(Math.max(...values)), median: round(valueMedian), mean: round(yMean), range: round(Math.max(...values) - Math.min(...values)), standardDeviation: round(deviation(values)), mad: mad === null ? null : round(mad), startEndDelta: round(values.at(-1)! - values[0]!), largestDelta: round(largestDelta), slopePerMinute: round(slope), volatility: round(deltas.length ? mean(deltas.map(Math.abs)) : 0) }
}

function ranks(values: number[]): number[] {
  const ordered = values.map((value, index) => ({ value, index })).sort((a, b) => a.value - b.value); const result = new Array<number>(values.length)
  for (let start = 0; start < ordered.length;) { let end = start + 1; while (end < ordered.length && ordered[end]!.value === ordered[start]!.value) end += 1; const rank = (start + end - 1) / 2 + 1; for (let index = start; index < end; index += 1) result[ordered[index]!.index] = rank; start = end }
  return result
}
function correlation(left: number[], right: number[]): number | null {
  if (left.length !== right.length || left.length < 2 || deviation(left) < INDUSTRIAL_ANALYTICS_RULES.minimumVariance || deviation(right) < INDUSTRIAL_ANALYTICS_RULES.minimumVariance) return null
  const leftMean = mean(left); const rightMean = mean(right); const numerator = left.reduce((sum, value, index) => sum + (value - leftMean) * (right[index]! - rightMean), 0)
  const denominator = Math.sqrt(left.reduce((sum, value) => sum + (value - leftMean) ** 2, 0) * right.reduce((sum, value) => sum + (value - rightMean) ** 2, 0))
  return denominator > 0 ? round(numerator / denominator) : null
}
function align(left: IndustrialNumericSample[], right: IndustrialNumericSample[], lagMs: number, toleranceMs: number) {
  const rightTimes = right.map((item) => Date.parse(item.atUtc)); const nextParent = Array.from({ length: right.length + 1 }, (_item, index) => index); const previousParent = Array.from({ length: right.length + 1 }, (_item, index) => index)
  const nextAvailable = (start: number): number => { let value = Math.max(0, Math.min(right.length, start)); while (nextParent[value] !== value) { nextParent[value] = nextParent[nextParent[value]!]!; value = nextParent[value]! } return value }
  const previousAvailablePosition = (startPosition: number): number => { let value = Math.max(0, Math.min(right.length, startPosition)); while (previousParent[value] !== value) { previousParent[value] = previousParent[previousParent[value]!]!; value = previousParent[value]! } return value }
  const remove = (index: number) => { nextParent[index] = nextAvailable(index + 1); previousParent[index + 1] = previousAvailablePosition(index) }
  const lowerBound = (target: number) => { let low = 0; let high = rightTimes.length; while (low < high) { const middle = (low + high) >>> 1; if (rightTimes[middle]! < target) low = middle + 1; else high = middle } return low }
  const pairs: Array<{ left: number; right: number; leftAtUtc: string; rightAtUtc: string }> = []
  for (const item of left) {
    const target = Date.parse(item.atUtc) + lagMs; const insertion = lowerBound(target); const later = nextAvailable(insertion); const earlierPosition = previousAvailablePosition(insertion); const earlier = earlierPosition - 1
    const earlierDistance = earlier >= 0 ? Math.abs(rightTimes[earlier]! - target) : Infinity; const laterDistance = later < right.length ? Math.abs(rightTimes[later]! - target) : Infinity
    const bestIndex = earlierDistance <= laterDistance ? earlier : later
    if (bestIndex >= 0 && bestIndex < right.length && Math.min(earlierDistance, laterDistance) <= toleranceMs) { remove(bestIndex); pairs.push({ left: item.value, right: right[bestIndex]!.value, leftAtUtc: item.atUtc, rightAtUtc: right[bestIndex]!.atUtc }) }
  }
  return pairs
}

function alignedTemporalCoverage(pairs: ReturnType<typeof align>, range: { start: string; end: string }): number {
  if (pairs.length < 2 || !validRange(range)) return 0
  const times = pairs.flatMap((pair) => [Date.parse(pair.leftAtUtc), Date.parse(pair.rightAtUtc)]).filter(Number.isFinite)
  return round(Math.min(100, Math.max(0, (Math.max(...times) - Math.min(...times)) / (Date.parse(range.end) - Date.parse(range.start)) * 100)), 1)
}

interface EnvelopeEpisode extends ThresholdDetection { direction: 'above' | 'below' }
function envelopeAnalysis(input: { samples: IndustrialNumericSample[]; range: { start: string; end: string }; event: { start: string; end: string } }) {
  const samples = numericSamples(input.samples, input.range); const before = samples.filter((sample) => Date.parse(sample.atUtc) < Date.parse(input.event.start)); const stats = describeIndustrialNumeric(before)
  if (!stats || stats.count < INDUSTRIAL_ANALYTICS_RULES.minimumNumericSamples) return { samples, before, stats, lower: null, upper: null, episodes: [] as EnvelopeEpisode[] }
  const scale = Math.max((stats.mad ?? 0) * 1.4826, stats.standardDeviation, Math.abs(stats.median) * .02, INDUSTRIAL_ANALYTICS_RULES.minimumVariance); const lower = stats.median - 3 * scale; const upper = stats.median + 3 * scale; const seed = before.at(-1) ?? null
  const afterStart = samples.filter((sample) => Date.parse(sample.atUtc) >= Date.parse(input.event.start)); const upperEpisodes = detectThresholdEvents({ observations: afterStart, fromUtc: input.event.start, toUtc: input.range.end, rule: { operator: '>', threshold: upper }, seed }).map((episode) => ({ ...episode, direction: 'above' as const })); const lowerEpisodes = detectThresholdEvents({ observations: afterStart, fromUtc: input.event.start, toUtc: input.range.end, rule: { operator: '<', threshold: lower }, seed }).map((episode) => ({ ...episode, direction: 'below' as const }))
  return { samples, before, stats, lower, upper, episodes: [...upperEpisodes, ...lowerEpisodes].sort((left, right) => Date.parse(left.startUtc) - Date.parse(right.startUtc) || left.direction.localeCompare(right.direction)) }
}

function observationTimestamp(observation: IndustrialAnalyticalObservation): string | null {
  const keys = ['firstDepartureAtUtc', 'firstDeltaAtUtc', 'firstTransitionAtUtc', 'firstSequenceDivergenceAtUtc', 'restartAtUtc', 'sustainedAtUtc']
  for (const key of keys) { const value = observation.metrics[key]; if (typeof value === 'string' && Number.isFinite(Date.parse(value))) return value }
  return null
}

export class IndustrialAnalyticsService {
  contextualTelemetryBaseline(input: { pressKey: RadiusPressKey; eventId: string; variableId: string; feature: string; unit?: string | null; range: { start: string; end: string }; currentValue: number; currentSampleCount: number; currentCoveragePercent: number; historical: Array<{ value: number; coveragePercent: number; range: { start: string; end: string } }>; baselineType: 'context' | 'episode'; matchingDimensions: string[]; fallbackLevel: number }): IndustrialAnalyticalObservation {
    const supported = input.historical.filter((item) => Number.isFinite(item.value) && item.coveragePercent >= INDUSTRIAL_ANALYTICS_RULES.minimumBaselineCoveragePercent)
    const reference = supported.length ? median(supported.map((item) => item.value)) : null; const spread = reference === null ? null : median(supported.map((item) => Math.abs(item.value - reference)))
    const delta = reference === null ? null : round(input.currentValue - reference); const adequate = supported.length >= 3 && input.currentCoveragePercent >= INDUSTRIAL_ANALYTICS_RULES.minimumBaselineCoveragePercent
    const scale = Math.max((spread ?? 0) * 1.4826, Math.abs(reference ?? input.currentValue) * .05, INDUSTRIAL_ANALYTICS_RULES.minimumVariance); const standardized = delta === null ? null : round(delta / scale)
    return { observationId: observationId(['contextual-telemetry', input.pressKey, input.eventId, input.variableId, input.feature, input.baselineType, input.matchingDimensions, input.fallbackLevel]), family: 'contextual_telemetry_baseline', pressKey: input.pressKey, deckNumber: null, range: input.range, comparisonRange: supported.length ? { start: supported.reduce((value, item) => Date.parse(item.range.start) < Date.parse(value) ? item.range.start : value, supported[0]!.range.start), end: supported.reduce((value, item) => Date.parse(item.range.end) > Date.parse(value) ? item.range.end : value, supported[0]!.range.end) } : null, eventId: input.eventId, variableIds: [input.variableId], factIds: [], metrics: { feature: input.feature, unit: input.unit ?? null, current: round(input.currentValue), historicalMedian: reference === null ? null : round(reference), historicalMad: spread === null ? null : round(spread), delta, standardizedDelta: standardized, baselineType: input.baselineType, matchingDimensions: input.matchingDimensions.join(' + '), sampleCount: supported.length, fallbackLevel: input.fallbackLevel }, support: { sampleCount: input.currentSampleCount, comparisonSampleCount: supported.length, coveragePercent: input.currentCoveragePercent, comparisonCoveragePercent: supported.length ? round(median(supported.map((item) => item.coveragePercent)), 1) : null, adequate, minimumRequired: 3, reason: adequate ? null : 'Contextual telemetry features require current coverage and at least three supported historical episodes.' }, evidenceSource: 'comparison', magnitudeInputs: { absoluteStandardizedDelta: standardized === null ? 0 : Math.abs(standardized), absoluteDelta: delta === null ? 0 : Math.abs(delta) }, material: adequate && standardized !== null && Math.abs(standardized) >= 2, limitations: adequate ? ['Feature distributions are compared across episodes; no point-by-point baseline trace is implied.'] : ['Insufficient contextual telemetry history; no abnormality is promoted from N<3.'], explorer: { href: `/telemetry-event-explorer?press=${input.pressKey}`, label: 'Open contextual telemetry evidence' } }
  }

  baselineDeviation(input: { pressKey: RadiusPressKey; range: { start: string; end: string }; comparisonRange: { start: string; end: string }; currentCoveragePercent: number; comparisonCoveragePercent: number; metrics: IndustrialBaselineMetricInput[] }): IndustrialAnalyticalObservation[] {
    const adequate = input.currentCoveragePercent >= INDUSTRIAL_ANALYTICS_RULES.minimumBaselineCoveragePercent && input.comparisonCoveragePercent >= INDUSTRIAL_ANALYTICS_RULES.minimumBaselineCoveragePercent
    return input.metrics.flatMap((metric) => {
      if (metric.current === null || metric.baseline === null) return []
      const delta = round(metric.current - metric.baseline); const magnitude = Math.abs(delta); const material = adequate && magnitude >= metric.materialDelta
      return [{ observationId: observationId(['baseline', input.pressKey, metric.metricId, input.range, input.comparisonRange]), family: 'baseline_deviation', pressKey: input.pressKey, deckNumber: null, range: input.range, comparisonRange: input.comparisonRange, eventId: null, variableIds: [metric.metricId], factIds: [metric.currentFactId, metric.baselineFactId, metric.deltaFactId], metrics: { label: metric.label, unit: metric.unit, current: round(metric.current), baseline: round(metric.baseline), delta, magnitude }, support: { sampleCount: metric.sampleCount ?? 1, comparisonSampleCount: metric.comparisonSampleCount ?? 1, coveragePercent: input.currentCoveragePercent, comparisonCoveragePercent: input.comparisonCoveragePercent, adequate, minimumRequired: INDUSTRIAL_ANALYTICS_RULES.minimumBaselineCoveragePercent, reason: adequate ? null : 'Current and comparison coverage must both be at least 80%.' }, evidenceSource: 'comparison', magnitudeInputs: { absoluteDelta: magnitude, materialThreshold: metric.materialDelta }, material, limitations: material ? [] : adequate ? ['Observed change is below the configured material-change threshold.'] : ['Insufficient current or comparison coverage.'], explorer: { href: `/overview?press=${input.pressKey}`, label: 'Open press overview' } } satisfies IndustrialAnalyticalObservation]
    })
  }

  robustNumericChange(input: { pressKey: RadiusPressKey; variableId: string; deckNumber?: number | null; unit?: string | null; range: { start: string; end: string }; samples: IndustrialNumericSample[]; eventId?: string | null }): IndustrialAnalyticalObservation | null {
    const samples = numericSamples(input.samples, input.range); const stats = describeIndustrialNumeric(samples); if (!stats) return null
    const adequate = stats.count >= INDUSTRIAL_ANALYTICS_RULES.minimumNumericSamples; const scale = Math.max(stats.mad ?? 0, stats.range * .1, Math.abs(stats.median) * .02, INDUSTRIAL_ANALYTICS_RULES.minimumVariance); const magnitude = Math.max(Math.abs(stats.startEndDelta), Math.abs(stats.largestDelta), stats.standardDeviation) / scale
    const byWindow = adequate ? [2, 5, 10, 20].map((windowMinutes) => ({ windowMinutes, events: detectDeltaEvents({ observations: samples, fromUtc: input.range.start, toUtc: input.range.end, rule: { direction: 'either', amount: scale * 2, windowMinutes } }) })) : []; const strongestWindow = byWindow.flatMap(({ windowMinutes, events }) => events.map((event) => ({ windowMinutes, event }))).sort((left, right) => Math.abs(right.event.maximumExcursion) - Math.abs(left.event.maximumExcursion) || left.windowMinutes - right.windowMinutes)[0]; const deltaEvents = strongestWindow ? byWindow.find((item) => item.windowMinutes === strongestWindow.windowMinutes)!.events : []
    return { observationId: observationId(['numeric', input.pressKey, input.variableId, input.deckNumber ?? null, input.range, input.eventId ?? null]), family: 'robust_numeric_change', pressKey: input.pressKey, deckNumber: input.deckNumber ?? null, range: input.range, comparisonRange: null, eventId: input.eventId ?? null, variableIds: [input.variableId], factIds: [], metrics: { unit: input.unit ?? null, ...stats, evaluatedDeltaWindowsMinutes: '2, 5, 10, 20', strongestDeltaWindowMinutes: strongestWindow?.windowMinutes ?? null, deltaEventCount: deltaEvents.length, largestEventExplorerDelta: strongestWindow ? round(strongestWindow.event.maximumExcursion) : null, firstDeltaAtUtc: deltaEvents[0]?.triggerAtUtc ?? null, longestDeltaEpisodeMinutes: deltaEvents.length ? round(Math.max(...deltaEvents.map((item) => item.durationSeconds)) / 60, 1) : null }, support: { sampleCount: stats.count, comparisonSampleCount: null, coveragePercent: spanCoverage(samples, input.range), comparisonCoveragePercent: null, adequate, minimumRequired: INDUSTRIAL_ANALYTICS_RULES.minimumNumericSamples, reason: adequate ? null : 'At least five usable numeric observations are required.' }, evidenceSource: 'telemetry', magnitudeInputs: { robustMagnitude: round(magnitude), scale: round(scale) }, material: adequate && magnitude >= 2, limitations: adequate ? [] : ['Insufficient numeric sample support.'], explorer: { href: `/telemetry-event-explorer?press=${input.pressKey}`, label: 'Open telemetry evidence' } }
  }

  eventAlignedNumeric(input: { pressKey: RadiusPressKey; variableId: string; deckNumber?: number | null; unit?: string | null; range: { start: string; end: string }; event: { id: string; start: string; end: string }; samples: IndustrialNumericSample[]; contextMinutes?: number }): IndustrialAnalyticalObservation | null {
    const contextMs = (input.contextMinutes ?? INDUSTRIAL_ANALYTICS_RULES.eventContextMinutes) * 60_000; const eventStart = Date.parse(input.event.start); const eventEnd = Date.parse(input.event.end); const range = { start: new Date(eventStart - contextMs).toISOString(), end: new Date(eventEnd + contextMs).toISOString() }
    const phase = (start: number, end: number, includeEnd = false) => describeIndustrialNumeric(numericSamples(input.samples, { start: new Date(start).toISOString(), end: new Date(end).toISOString() }).filter((sample) => includeEnd || Date.parse(sample.atUtc) < end))
    const before = phase(eventStart - contextMs, eventStart); const during = phase(eventStart, eventEnd); const after = phase(eventEnd, eventEnd + contextMs, true); if (!before && !during && !after) return null
    const adequate = Boolean(before && during && after && before.count >= INDUSTRIAL_ANALYTICS_RULES.minimumWindowSamples && during.count >= INDUSTRIAL_ANALYTICS_RULES.minimumWindowSamples && after.count >= INDUSTRIAL_ANALYTICS_RULES.minimumWindowSamples)
    const beforeToEvent = before && during ? round(during.median - before.median) : null; const eventToAfter = during && after ? round(after.median - during.median) : null; const scale = Math.max(before?.mad ?? 0, before?.range ?? 0, Math.abs(before?.median ?? 0) * .02, INDUSTRIAL_ANALYTICS_RULES.minimumVariance); const magnitude = beforeToEvent === null ? 0 : Math.abs(beforeToEvent) / scale
    return { observationId: observationId(['event', input.pressKey, input.variableId, input.deckNumber ?? null, input.event]), family: 'event_aligned_change', pressKey: input.pressKey, deckNumber: input.deckNumber ?? null, range, comparisonRange: null, eventId: input.event.id, variableIds: [input.variableId], factIds: [], metrics: { unit: input.unit ?? null, beforeMedian: before?.median ?? null, eventMedian: during?.median ?? null, afterMedian: after?.median ?? null, beforeToEventDelta: beforeToEvent, eventToAfterDelta: eventToAfter, eventMinimum: during?.minimum ?? null, eventMaximum: during?.maximum ?? null, eventSlopePerMinute: during?.slopePerMinute ?? null, eventVolatility: during?.volatility ?? null }, support: { sampleCount: (before?.count ?? 0) + (during?.count ?? 0) + (after?.count ?? 0), comparisonSampleCount: before?.count ?? 0, coveragePercent: spanCoverage(numericSamples(input.samples, range), range), comparisonCoveragePercent: null, adequate, minimumRequired: INDUSTRIAL_ANALYTICS_RULES.minimumWindowSamples, reason: adequate ? null : 'Before, event, and after windows each require at least three observations.' }, evidenceSource: 'telemetry', magnitudeInputs: { robustMagnitude: round(magnitude), baselineScale: round(scale) }, material: adequate && magnitude >= 2, limitations: adequate ? [] : ['Insufficient before/event/after support.'], explorer: { href: `/telemetry-event-explorer?press=${input.pressKey}`, label: 'Open event-aligned telemetry' } }
  }

  valueTransitions(input: { pressKey: RadiusPressKey; variableId: string; deckNumber?: number | null; range: { start: string; end: string }; samples: IndustrialStateSample[]; event?: { id: string; start: string; end: string } | null }): IndustrialAnalyticalObservation {
    const transitions = detectValueChangeEvents({ observations: input.samples, fromUtc: input.range.start, toUtc: input.range.end, rule: { match: 'any' } }); const intervals = transitions.slice(1).map((item, index) => (Date.parse(item.transitionAtUtc) - Date.parse(transitions[index]!.transitionAtUtc)) / 60_000); const nearEvent = input.event ? transitions.filter((item) => Date.parse(item.transitionAtUtc) >= Date.parse(input.event!.start) - 20 * 60_000 && Date.parse(item.transitionAtUtc) <= Date.parse(input.event!.end) + 20 * 60_000).length : 0
    const adequate = input.samples.length >= 2; return { observationId: observationId(['transition', input.pressKey, input.variableId, input.deckNumber ?? null, input.range, input.event?.id ?? null]), family: 'value_state_transition', pressKey: input.pressKey, deckNumber: input.deckNumber ?? null, range: input.range, comparisonRange: null, eventId: input.event?.id ?? null, variableIds: [input.variableId], factIds: [], metrics: { transitionCount: transitions.length, repeatedTransitionCount: Math.max(0, transitions.length - new Set(transitions.map((item) => `${String(item.previousValue)}>${String(item.newValue)}`)).size), medianMinutesBetweenTransitions: intervals.length ? round(median(intervals)) : null, transitionsNearEvent: nearEvent, firstTransitionAtUtc: transitions[0]?.transitionAtUtc ?? null, stateBefore: transitions[0]?.previousValue ?? input.samples[0]?.value ?? null, stateAfter: transitions.at(-1)?.newValue ?? input.samples.at(-1)?.value ?? null }, support: { sampleCount: input.samples.length, comparisonSampleCount: null, coveragePercent: null, comparisonCoveragePercent: null, adequate, minimumRequired: 2, reason: adequate ? null : 'At least two state observations are required.' }, evidenceSource: input.variableId.startsWith('production.') ? 'production_context' : 'telemetry', magnitudeInputs: { transitionCount: transitions.length, transitionsNearEvent: nearEvent }, material: adequate && (nearEvent > 0 || transitions.length >= 2), limitations: adequate ? [] : ['Insufficient state observations.'], explorer: { href: `/telemetry-event-explorer?press=${input.pressKey}`, label: 'Open transition evidence' } }
  }

  normalEnvelopeDeparture(input: { pressKey: RadiusPressKey; variableId: string; deckNumber?: number | null; unit?: string | null; range: { start: string; end: string }; event: { id: string; start: string; end: string }; samples: IndustrialNumericSample[] }): IndustrialAnalyticalObservation | null {
    const analysis = envelopeAnalysis(input); if (!analysis.samples.length) return null; const adequate = Boolean(analysis.stats && analysis.before.length >= INDUSTRIAL_ANALYTICS_RULES.minimumNumericSamples && analysis.lower !== null && analysis.upper !== null); const first = analysis.episodes[0]; const longest = analysis.episodes.length ? analysis.episodes.reduce((best, item) => item.durationSeconds > best.durationSeconds ? item : best) : null; const extremeMagnitude = analysis.episodes.length && analysis.stats && analysis.lower !== null && analysis.upper !== null ? Math.max(...analysis.episodes.map((item) => item.direction === 'above' ? item.extremeValue - analysis.upper! : analysis.lower! - item.extremeValue)) : 0
    return { observationId: observationId(['envelope', input.pressKey, input.variableId, input.deckNumber ?? null, input.event.id]), family: 'normal_envelope_departure', pressKey: input.pressKey, deckNumber: input.deckNumber ?? null, range: input.range, comparisonRange: { start: input.range.start, end: input.event.start }, eventId: input.event.id, variableIds: [input.variableId], factIds: [], metrics: { unit: input.unit ?? null, evidenceType: 'context_derived_normal_envelope', expectedMedian: analysis.stats?.median ?? null, envelopeLower: analysis.lower === null ? null : round(analysis.lower), envelopeUpper: analysis.upper === null ? null : round(analysis.upper), firstDepartureAtUtc: first?.startUtc ?? null, firstDepartureDirection: first?.direction ?? null, firstExtremeValue: first?.extremeValue ?? null, recurrenceCount: analysis.episodes.length, longestDurationMinutes: longest ? round(longest.durationSeconds / 60, 1) : null, maximumDepartureMagnitude: round(extremeMagnitude) }, support: { sampleCount: analysis.samples.length, comparisonSampleCount: analysis.before.length, coveragePercent: spanCoverage(analysis.samples, input.range), comparisonCoveragePercent: spanCoverage(analysis.before, { start: input.range.start, end: input.event.start }), adequate, minimumRequired: INDUSTRIAL_ANALYTICS_RULES.minimumNumericSamples, reason: adequate ? null : 'At least five usable pre-event observations are required to derive a normal envelope.' }, evidenceSource: 'telemetry', magnitudeInputs: { maximumDepartureMagnitude: round(extremeMagnitude), recurrenceCount: analysis.episodes.length }, material: adequate && analysis.episodes.length > 0, limitations: ['This is a context-derived statistical envelope, not an operator-configured threshold or limit.'], explorer: { href: `/telemetry-event-explorer?press=${input.pressKey}`, label: 'Open envelope evidence' } }
  }

  deviationPersistence(input: Parameters<IndustrialAnalyticsService['normalEnvelopeDeparture']>[0]): IndustrialAnalyticalObservation | null {
    const analysis = envelopeAnalysis(input); if (!analysis.episodes.length || !analysis.stats || analysis.lower === null || analysis.upper === null) return null; const first = analysis.episodes[0]!; const last = analysis.episodes.at(-1)!; const longest = analysis.episodes.reduce((best, item) => item.durationSeconds > best.durationSeconds ? item : best); const totalSeconds = analysis.episodes.reduce((sum, item) => sum + item.durationSeconds, 0); const classification = analysis.episodes.length > 1 ? 'repeated' : longest.durationSeconds >= 120 ? 'sustained' : 'isolated'
    return { observationId: observationId(['persistence', input.pressKey, input.variableId, input.deckNumber ?? null, input.event.id]), family: 'deviation_persistence', pressKey: input.pressKey, deckNumber: input.deckNumber ?? null, range: { start: first.startUtc, end: last.endUtc }, comparisonRange: { start: input.range.start, end: input.event.start }, eventId: input.event.id, variableIds: [input.variableId], factIds: [], metrics: { unit: input.unit ?? null, classification, startAtUtc: first.startUtc, endAtUtc: last.endUtc, totalDurationMinutes: round(totalSeconds / 60, 1), longestDurationMinutes: round(longest.durationSeconds / 60, 1), recurrenceCount: analysis.episodes.length, maximumMagnitude: round(Math.max(...analysis.episodes.map((item) => item.direction === 'above' ? item.extremeValue - analysis.upper! : analysis.lower! - item.extremeValue))) }, support: { sampleCount: analysis.samples.length, comparisonSampleCount: analysis.before.length, coveragePercent: spanCoverage(analysis.samples, input.range), comparisonCoveragePercent: spanCoverage(analysis.before, { start: input.range.start, end: input.event.start }), adequate: true, minimumRequired: INDUSTRIAL_ANALYTICS_RULES.minimumNumericSamples, reason: null }, evidenceSource: 'telemetry', magnitudeInputs: { totalDurationMinutes: round(totalSeconds / 60, 1), recurrenceCount: analysis.episodes.length }, material: classification !== 'isolated' || totalSeconds >= 60, limitations: ['Persistence groups adjacent out-of-envelope samples into bounded episodes; it does not establish causation.'], explorer: { href: `/telemetry-event-explorer?press=${input.pressKey}`, label: 'Open persistence evidence' } }
  }

  firstDivergence(input: { pressKey: RadiusPressKey; event: { id: string; start: string; end: string }; observations: IndustrialAnalyticalObservation[]; cadenceMinutes?: number }): IndustrialAnalyticalObservation | null {
    const candidates = input.observations.filter((item) => item.support.adequate && item.material).flatMap((item) => { const atUtc = observationTimestamp(item); return atUtc ? [{ item, atUtc }] : [] }).sort((left, right) => Date.parse(left.atUtc) - Date.parse(right.atUtc) || left.item.observationId.localeCompare(right.item.observationId)); const first = candidates[0]; if (!first) return null; const relativeMinutes = round((Date.parse(first.atUtc) - Date.parse(input.event.start)) / 60_000, 1); const observed = first.item.family === 'normal_envelope_departure' ? `${String(first.item.metrics.firstDepartureDirection)} expected envelope` : first.item.family === 'value_state_transition' ? `${String(first.item.metrics.stateBefore)} to ${String(first.item.metrics.stateAfter)}` : first.item.family === 'robust_numeric_change' ? `numeric delta ${String(first.item.metrics.largestEventExplorerDelta)}` : first.item.family; const expected = first.item.family === 'normal_envelope_departure' ? `${String(first.item.metrics.envelopeLower)} to ${String(first.item.metrics.envelopeUpper)}` : 'matched pre-event behavior'
    const cadence = Math.max(0, input.cadenceMinutes ?? 0); const ordering = relativeMinutes === 0 ? 'SAME_RECORDED_TIME' : cadence > 0 && Math.abs(relativeMinutes) <= cadence / 2 ? 'INDETERMINATE_WITHIN_CADENCE' : relativeMinutes < 0 ? 'BEFORE' : 'AFTER'
    return { observationId: observationId(['first-divergence', input.pressKey, input.event.id, first.item.observationId]), family: 'first_divergence', pressKey: input.pressKey, deckNumber: first.item.deckNumber, range: { start: first.atUtc, end: first.atUtc }, comparisonRange: first.item.comparisonRange, eventId: input.event.id, variableIds: first.item.variableIds, factIds: [], metrics: { firstObservedAtUtc: first.atUtc, relativeToEpisodeMinutes: relativeMinutes, ordering, cadenceMinutes: cadence || null, sourceFamily: first.item.family, signal: first.item.variableIds.join(' + '), observedBehavior: observed, expectedBehavior: expected, orderingResolution: ordering === 'INDETERMINATE_WITHIN_CADENCE' ? 'sampling_cadence_bound' : 'sample_or_radius_transition_timestamp', candidateLanguage: 'earliest supported departure; candidate investigation lead' }, support: { ...first.item.support }, evidenceSource: first.item.evidenceSource, magnitudeInputs: { orderingMinutes: Math.abs(relativeMinutes), sourceMagnitude: Math.max(0, ...Object.values(first.item.magnitudeInputs).filter((value): value is number => typeof value === 'number').map(Math.abs)) }, material: true, limitations: ['Temporal ordering identifies the first observed supported departure in the bounded evidence; it is not a root-cause conclusion.', ...(ordering === 'INDETERMINATE_WITHIN_CADENCE' ? ['The observed timestamps are too close relative to sampling cadence to establish before/after ordering.'] : [])], explorer: first.item.explorer }
  }

  radiusTelemetryAlignment(input: { pressKey: RadiusPressKey; event: { id: string; start: string; end: string }; observations: IndustrialAnalyticalObservation[]; cadenceMinutes?: number }): IndustrialAnalyticalObservation | null {
    const telemetry = input.observations.filter((item) => item.evidenceSource === 'telemetry' && item.support.adequate && item.material).flatMap((item) => { const atUtc = observationTimestamp(item); return atUtc ? [{ item, atUtc }] : [] }).sort((left, right) => Date.parse(left.atUtc) - Date.parse(right.atUtc) || left.item.observationId.localeCompare(right.item.observationId))[0]; if (!telemetry) return null; const lagMinutes = round((Date.parse(telemetry.atUtc) - Date.parse(input.event.start)) / 60_000, 1); const cadence = Math.max(0, input.cadenceMinutes ?? 0); const relation = lagMinutes === 0 ? 'SAME_RECORDED_TIME' : cadence > 0 && Math.abs(lagMinutes) <= cadence / 2 ? 'INDETERMINATE_WITHIN_CADENCE' : lagMinutes > 0 ? 'RADIUS_PRECEDED_TELEMETRY' : 'TELEMETRY_PRECEDED_RADIUS'; const statement = relation === 'INDETERMINATE_WITHIN_CADENCE' ? 'Radius and telemetry ordering is indeterminate within the observed sampling cadence.' : lagMinutes > 0 ? `Radius episode transition preceded the first supported telemetry behavior by ${lagMinutes} minutes.` : lagMinutes < 0 ? `The first supported telemetry behavior preceded the Radius episode transition by ${Math.abs(lagMinutes)} minutes.` : 'Radius and telemetry transitions share the same recorded timestamp.'
    return { observationId: observationId(['alignment', input.pressKey, input.event.id, telemetry.item.observationId]), family: 'radius_telemetry_alignment', pressKey: input.pressKey, deckNumber: telemetry.item.deckNumber, range: { start: new Date(Math.min(Date.parse(input.event.start), Date.parse(telemetry.atUtc))).toISOString(), end: new Date(Math.max(Date.parse(input.event.start), Date.parse(telemetry.atUtc))).toISOString() }, comparisonRange: null, eventId: input.event.id, variableIds: ['radius.sequence', ...telemetry.item.variableIds], factIds: [], metrics: { relation, lagMinutes, radiusTransitionAtUtc: input.event.start, telemetryBehaviorAtUtc: telemetry.atUtc, telemetryFamily: telemetry.item.family, statement }, support: { sampleCount: telemetry.item.support.sampleCount, comparisonSampleCount: 1, coveragePercent: telemetry.item.support.coveragePercent, comparisonCoveragePercent: null, adequate: true, minimumRequired: 1, reason: null }, evidenceSource: 'comparison', magnitudeInputs: { absoluteLagMinutes: Math.abs(lagMinutes) }, material: true, limitations: ['This alignment compares observed timing only and does not infer operator intent or causation.'], explorer: telemetry.item.explorer }
  }

  numericRelationship(input: { pressKey: RadiusPressKey; leftVariableId: string; rightVariableId: string; range: { start: string; end: string }; left: IndustrialNumericSample[]; right: IndustrialNumericSample[]; context?: string; basis?: 'LEVELS' | 'DIFFERENCES'; scope?: 'WHOLE_WINDOW' | 'EVENT_WINDOW' | 'CONTEXT'; minimumPairs?: number; maximumLagMinutes?: number; lagStepMinutes?: number; alignmentToleranceMs?: number }): IndustrialRelationshipResult | null {
    const difference = (values: IndustrialNumericSample[]) => values.slice(1).map((item, index) => ({ atUtc: item.atUtc, value: item.value - values[index]!.value, qualityState: item.qualityState }))
    const left = numericSamples(input.basis === 'DIFFERENCES' ? difference(numericSamples(input.left)) : input.left); const right = numericSamples(input.basis === 'DIFFERENCES' ? difference(numericSamples(input.right)) : input.right)
    const minimum = input.minimumPairs ?? INDUSTRIAL_ANALYTICS_RULES.minimumRelationshipPairs; const tolerance = input.alignmentToleranceMs ?? INDUSTRIAL_ANALYTICS_RULES.alignmentToleranceMs; const base = align(left, right, 0, tolerance); if (base.length < minimum) return null
    const pearson = correlation(base.map(({ left }) => left), base.map(({ right }) => right)); const spearman = correlation(ranks(base.map(({ left }) => left)), ranks(base.map(({ right }) => right))); if (pearson === null || spearman === null) return null
    let best = { lag: 0, correlation: pearson, pairs: base }; const maximumLag = input.maximumLagMinutes ?? INDUSTRIAL_ANALYTICS_RULES.maximumLagMinutes; const lagStep = input.lagStepMinutes ?? INDUSTRIAL_ANALYTICS_RULES.lagStepMinutes
    for (let lag = -maximumLag; lag <= maximumLag; lag += lagStep) { const pairs = align(left, right, lag * 60_000, tolerance); if (pairs.length < minimum) continue; const value = correlation(pairs.map(({ left }) => left), pairs.map(({ right }) => right)); if (value !== null && (Math.abs(value) > Math.abs(best.correlation) + 1e-9 || Math.abs(value) === Math.abs(best.correlation) && Math.abs(lag) < Math.abs(best.lag))) best = { lag, correlation: value, pairs } }
    const coveragePercent = round(best.pairs.length / Math.max(left.length, right.length) * 100, 1); const temporalCoveragePercent = alignedTemporalCoverage(best.pairs, input.range)
    const qualification = best.pairs.length < minimum ? 'INSUFFICIENT_PAIRS' : coveragePercent < INDUSTRIAL_ANALYTICS_RULES.minimumRelationshipPairCoveragePercent ? 'LOW_PAIR_COVERAGE' : temporalCoveragePercent < INDUSTRIAL_ANALYTICS_RULES.minimumRelationshipTemporalCoveragePercent ? 'LOW_TEMPORAL_COVERAGE' : 'QUALIFIED'
    return { basis: input.basis ?? 'LEVELS', scope: input.scope ?? (input.context ? 'CONTEXT' : 'WHOLE_WINDOW'), pearson, spearman, bestLagMinutes: best.lag, bestLagCorrelation: best.correlation, sampleCount: best.pairs.length, coveragePercent, temporalCoveragePercent, qualified: qualification === 'QUALIFIED', qualification }
  }

  relationshipObservation(input: Parameters<IndustrialAnalyticsService['numericRelationship']>[0]): IndustrialAnalyticalObservation | null {
    const result = this.numericRelationship(input); if (!result) return null; const change = result.basis === 'LEVELS' ? this.numericRelationship({ ...input, basis: 'DIFFERENCES' }) : null; const levelsOnlyContradicted = Boolean(change?.qualified && Math.abs(change.bestLagCorrelation) < .4); const strong = Math.abs(result.bestLagCorrelation) >= .7 && !levelsOnlyContradicted; const adequate = result.qualified
    return { observationId: observationId(['relationship', input.pressKey, input.leftVariableId, input.rightVariableId, input.range, input.context ?? 'overall', result.basis, result.scope]), family: 'numeric_relationship', pressKey: input.pressKey, deckNumber: null, range: input.range, comparisonRange: null, eventId: null, variableIds: [input.leftVariableId, input.rightVariableId], factIds: [], metrics: { context: input.context ?? 'overall', basis: result.basis, scope: result.scope, pearson: result.pearson, spearman: result.spearman, bestLagMinutes: result.bestLagMinutes, bestLagCorrelation: result.bestLagCorrelation, alignedPairCount: result.sampleCount, pairCoveragePercent: result.coveragePercent, temporalCoveragePercent: result.temporalCoveragePercent, qualification: result.qualification, changeBasisCoefficient: change?.bestLagCorrelation ?? null, changeBasisQualification: change?.qualification ?? null, direction: result.bestLagMinutes > 0 ? `${input.leftVariableId} leads ${input.rightVariableId}` : result.bestLagMinutes < 0 ? `${input.rightVariableId} leads ${input.leftVariableId}` : 'no detected lead' }, support: { sampleCount: result.sampleCount, comparisonSampleCount: change?.sampleCount ?? null, coveragePercent: result.coveragePercent, comparisonCoveragePercent: result.temporalCoveragePercent, adequate, minimumRequired: input.minimumPairs ?? INDUSTRIAL_ANALYTICS_RULES.minimumRelationshipPairs, reason: adequate ? levelsOnlyContradicted ? 'Levels correlation was not supported by change-based relationship evidence.' : null : result.qualification === 'LOW_PAIR_COVERAGE' ? `Aligned pairs cover less than ${INDUSTRIAL_ANALYTICS_RULES.minimumRelationshipPairCoveragePercent}% of the denser series.` : `Aligned pairs span less than ${INDUSTRIAL_ANALYTICS_RULES.minimumRelationshipTemporalCoveragePercent}% of the requested window.` }, evidenceSource: 'telemetry', magnitudeInputs: { absoluteCorrelation: Math.abs(result.bestLagCorrelation), lagMinutes: result.bestLagMinutes, pairCoveragePercent: result.coveragePercent, temporalCoveragePercent: result.temporalCoveragePercent }, material: adequate && strong, limitations: [...(adequate ? [] : ['Relationship retained in diagnostics only because aligned data coverage is insufficient.']), ...(levelsOnlyContradicted ? ['A levels-only correlation was not promoted because change-based evidence did not support it.'] : []), 'Correlation is association evidence and does not establish causation.'], explorer: { href: `/telemetry-event-explorer?press=${input.pressKey}`, label: 'Open relationship evidence' } }
  }

  crossPressComparison(input: { canonicalId: string; range: { start: string; end: string }; series: Array<{ pressKey: RadiusPressKey; samples: IndustrialNumericSample[] }> }): IndustrialAnalyticalObservation[] {
    const supported = input.series.flatMap((item) => { const stats = describeIndustrialNumeric(numericSamples(item.samples, input.range)); return stats && stats.count >= INDUSTRIAL_ANALYTICS_RULES.minimumNumericSamples ? [{ ...item, stats }] : [] })
    if (supported.length < INDUSTRIAL_ANALYTICS_RULES.minimumCrossPressSeries) return []
    const fleetMedian = median(supported.map(({ stats }) => stats.median))
    return supported.map(({ pressKey, stats, samples }) => {
      const delta = round(stats.median - fleetMedian)
      return {
        observationId: observationId(['cross-press', input.canonicalId, pressKey, input.range]),
        family: 'cross_press_comparison',
        pressKey,
        deckNumber: null,
        range: input.range,
        comparisonRange: input.range,
        eventId: null,
        variableIds: [input.canonicalId],
        factIds: [],
        metrics: { pressMedian: stats.median, compatiblePressMedian: round(fleetMedian), delta, slopePerMinute: stats.slopePerMinute, volatility: stats.volatility },
        support: { sampleCount: stats.count, comparisonSampleCount: supported.length - 1, coveragePercent: spanCoverage(samples, input.range), comparisonCoveragePercent: null, adequate: true, minimumRequired: INDUSTRIAL_ANALYTICS_RULES.minimumCrossPressSeries, reason: null },
        evidenceSource: 'comparison',
        magnitudeInputs: { absoluteMedianDelta: Math.abs(delta) },
        material: Math.abs(delta) >= Math.max(Math.abs(fleetMedian) * .2, stats.mad ?? 0, INDUSTRIAL_ANALYTICS_RULES.minimumVariance),
        limitations: ['Compared only through the same trusted canonical concept; press series remained independent.'],
        explorer: { href: `/overview?press=${pressKey}`, label: 'Open compatible-press evidence' },
      } satisfies IndustrialAnalyticalObservation
    })
  }

  crossPressSummaryComparison(input: { canonicalId: string; unit?: string | null; range: { start: string; end: string }; values: Array<{ pressKey: RadiusPressKey; value: number | null; supportCount: number; coveragePercent: number | null; factId: string }> }): IndustrialAnalyticalObservation[] {
    const supported = input.values.filter((item): item is typeof item & { value: number; coveragePercent: number } => item.value !== null && item.coveragePercent !== null && item.coveragePercent >= INDUSTRIAL_ANALYTICS_RULES.minimumBaselineCoveragePercent)
    if (supported.length < INDUSTRIAL_ANALYTICS_RULES.minimumCrossPressSeries) return []
    const compatibleMedian = median(supported.map(({ value }) => value))
    const deviations = supported.map(({ value }) => Math.abs(value - compatibleMedian))
    const materialThreshold = Math.max(median(deviations) * 2, Math.abs(compatibleMedian) * .2, INDUSTRIAL_ANALYTICS_RULES.minimumVariance)
    return supported.map((item) => {
      const delta = round(item.value - compatibleMedian)
      return {
        observationId: observationId(['cross-press-summary', input.canonicalId, item.pressKey, input.range]),
        family: 'cross_press_comparison',
        pressKey: item.pressKey,
        deckNumber: null,
        range: input.range,
        comparisonRange: input.range,
        eventId: null,
        variableIds: [input.canonicalId],
        factIds: [item.factId],
        metrics: { unit: input.unit ?? null, pressValue: round(item.value), compatiblePressMedian: round(compatibleMedian), delta },
        support: { sampleCount: item.supportCount, comparisonSampleCount: supported.length - 1, coveragePercent: item.coveragePercent, comparisonCoveragePercent: null, adequate: true, minimumRequired: INDUSTRIAL_ANALYTICS_RULES.minimumCrossPressSeries, reason: null },
        evidenceSource: 'comparison',
        magnitudeInputs: { absoluteDelta: Math.abs(delta), materialThreshold: round(materialThreshold) },
        material: Math.abs(delta) >= materialThreshold,
        limitations: ['Compared only through the same deterministic Radius metric and time range; press records remained independent.'],
        explorer: { href: `/overview?press=${item.pressKey}`, label: 'Open compatible-press evidence' },
      } satisfies IndustrialAnalyticalObservation
    })
  }
}
