import { useEffect, useMemo, useState } from 'react'
import { getChangeoverInspector, getChangeoverIntelligenceReport } from '../api/process-intelligence-api'
import type { RadiusPressKey } from '../types/api'
import type { ChangeoverEvent, ChangeoverInspector, ChangeoverMode, ChangeoverPhase, ChangeoverReport, ChangeoverRequest } from '../types/changeover'

const DEFAULTS = { stopSpeed: 1, recoverySpeed: 500, recoveryConfirmationSeconds: 300 }
type Preset = 'today' | '24h' | '7d' | '30d' | '90d' | 'last' | 'custom' | 'all'
interface Props { selectedPress?: RadiusPressKey; onPressChange(pressKey: RadiusPressKey | undefined): void }

function rangeFor(preset: Preset, lastDays = 14) {
  const to = new Date(); const from = new Date(to)
  if (preset === 'today') from.setHours(0, 0, 0, 0)
  else if (preset === '24h') from.setTime(to.getTime() - 24 * 60 * 60_000)
  else if (preset === 'all') from.setUTCFullYear(from.getUTCFullYear() - 10)
  else from.setTime(to.getTime() - (preset === 'last' ? lastDays : Number.parseInt(preset)) * 24 * 60 * 60_000)
  return { fromUtc: from.toISOString(), toUtc: to.toISOString() }
}
const duration = (value: number | null) => value === null ? '—' : value >= 3600 ? `${Math.round(value / 360) / 10} h` : value >= 60 ? `${Math.round(value / 6) / 10} min` : `${Math.round(value)} sec`
const time = (value: string | null) => value ? new Intl.DateTimeFormat('en-US', { timeZone: 'America/Chicago', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit', second: '2-digit' }).format(new Date(value)) : '—'
const phaseLabel = (phase: ChangeoverPhase) => phase.replaceAll('_', ' ').toLowerCase().replace(/^./, (value) => value.toUpperCase())
const evidenceLabel = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/^./, (item) => item.toUpperCase())
const localDate = (value: string) => new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Chicago', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date(value)).reduce((parts, item) => item.type === 'year' || item.type === 'month' || item.type === 'day' ? { ...parts, [item.type]: item.value } : parts, {} as Record<string, string>)
const localDateKey = (value: string) => { const parts = localDate(value); return `${parts.year}-${parts.month}-${parts.day}` }
const medianValue = (values: number[]) => { const ordered = values.filter(Number.isFinite).sort((a, b) => a - b); const middle = Math.floor(ordered.length / 2); return !ordered.length ? null : ordered.length % 2 ? ordered[middle]! : (ordered[middle - 1]! + ordered[middle]!) / 2 }

function Support({ level, count }: { level: string; count: number }) { return <span className={`co-support co-support--${level}`}>{level} · N={count}</span> }

function Distribution({ value }: { value: ChangeoverReport['duration'] }) {
  return <span className="co-distribution"><strong>{duration(value.median)}</strong><small>P25 {duration(value.p25)} · P75 {duration(value.p75)} · P90 {duration(value.p90)} · IQR {duration(value.iqr)}</small></span>
}

function SpeedChart({ inspector }: { inspector: ChangeoverInspector }) {
  const numeric = inspector.speed.samples.flatMap((sample) => typeof sample.value === 'number' && Number.isFinite(sample.value) ? [{ at: Date.parse(sample.observedAtUtc), value: sample.value }] : [])
  const start = Math.min(...numeric.map(({ at }) => at), Date.parse(inspector.event.physical.physicalStartUtc)); const end = Math.max(...numeric.map(({ at }) => at), Date.parse(inspector.event.physical.recoveryConfirmedAtUtc ?? inspector.event.physical.physicalRecoveryUtc ?? inspector.event.physical.physicalStartUtc)); const maximum = Math.max(inspector.definition.recoverySpeed * 1.2, ...numeric.map(({ value }) => value), 1)
  const x = (at: number) => 20 + (at - start) / Math.max(1, end - start) * 760; const y = (value: number) => 180 - value / maximum * 145
  const path = numeric.map((point, index) => `${index ? 'L' : 'M'}${x(point.at).toFixed(1)},${y(point.value).toFixed(1)}`).join(' ')
  const marker = (atUtc: string | null, className: string, label: string) => atUtc ? <g className={className}><line x1={x(Date.parse(atUtc))} x2={x(Date.parse(atUtc))} y1="18" y2="185"/><text x={x(Date.parse(atUtc)) + 4} y="30">{label}</text></g> : null
  return <div className="co-speed-chart"><svg viewBox="0 0 800 205" role="img" aria-label="Actual speed with physical stop, recovery candidates, failed attempts, and recovery confirmation"><line className="co-threshold co-threshold--recovery" x1="20" x2="780" y1={y(inspector.definition.recoverySpeed)} y2={y(inspector.definition.recoverySpeed)} /><line className="co-threshold co-threshold--stop" x1="20" x2="780" y1={y(inspector.definition.stopSpeed)} y2={y(inspector.definition.stopSpeed)} /><path className="co-speed-line" d={path}/>{marker(inspector.event.physical.physicalStartUtc, 'co-stop-marker', 'physical stop')}{inspector.event.physical.failedRecoveryAttempts.map((attempt, index) => <g key={attempt.candidateStartUtc}>{marker(attempt.candidateStartUtc, 'co-failed-marker', `failed ${index + 1}`)}</g>)}{marker(inspector.event.physical.physicalRecoveryUtc, 'co-recovery-marker', 'recovery start')}{marker(inspector.event.physical.recoveryConfirmedAtUtc, 'co-confirm-marker', 'confirmed')}</svg><small>Actual speed ({inspector.speed.sourceUnit ?? 'source unit'}). Recovery begins {time(inspector.event.physical.physicalRecoveryUtc)} and is confirmed sustained through {time(inspector.event.physical.recoveryConfirmedAtUtc)}; downtime ends at recovery start.</small></div>
}

function EvidenceTrack({ inspector }: { inspector: ChangeoverInspector }) {
  const event = inspector.event; const start = Date.parse(event.physical.physicalStartUtc); const end = Date.parse(event.physical.physicalRecoveryUtc ?? event.physical.physicalStartUtc); const position = (at: string) => Math.max(0, Math.min(100, (Date.parse(at) - start) / Math.max(1, end - start) * 100))
  return <div className="co-tracks">
    <div><strong>Order metadata</strong><div className="co-order-track">{inspector.orderTrack.filter((item) => Date.parse(item.atUtc) >= start - 300_000 && Date.parse(item.atUtc) <= end + 300_000).map((item, index) => <span key={`${item.atUtc}-${index}`} style={{ left: `${position(item.atUtc)}%` }} title={`${item.kind}: ${item.value ?? 'unavailable'} at ${time(item.atUtc)}`}>{item.kind === 'SETTLED' ? '◆' : '│'}</span>)}</div><small>First indication, last field change, and settled identity remain distinct.</small></div>
    <div><strong>Raw Radius</strong><div className="co-segment-track">{event.radius?.rawIntervals.map((item, index) => <span key={index} className={`co-phase--${item.isProduction ? 'RADIUS_PRODUCTION_MISMATCH' : item.kind === 'offline' ? 'RADIUS_DATA_GAP' : 'OTHER_RADIUS'}`} style={{ left: `${position(item.originalStartUtc)}%`, width: `${Math.max(1, position(item.originalEndUtc) - position(item.originalStartUtc))}%` }} title={`${item.identity.eventType ?? 'gap'} / ${item.identity.statusCode ?? '—'} ${item.identity.statusDescription ?? ''}`} />)}</div><small>Original timestamps; intervals may extend outside the physical window.</small></div>
    <div><strong>Adjusted physical window</strong><div className="co-segment-track">{event.radius?.adjustedContributions.map((item, index) => <span key={index} className={`co-phase--${item.phase}`} style={{ left: `${position(item.adjustedStartUtc)}%`, width: `${Math.max(1, position(item.adjustedEndUtc) - position(item.adjustedStartUtc))}%` }} title={`${phaseLabel(item.phase)} · ${duration(item.durationSeconds)}`} />)}</div><small>Clipped and reconciled to exactly {duration(event.physical.durationSeconds)}.</small></div>
  </div>
}

function Inspector({ value, loading, onClose }: { value?: ChangeoverInspector; loading: boolean; onClose(): void }) {
  if (loading) return <section className="panel co-inspector" role="status">Reconstructing bounded changeover evidence…</section>
  if (!value) return null
  const event = value.event; const transition = event.orderTransition
  return <section className="panel co-inspector" id="changeover-inspector"><div className="section-heading"><div><span className="eyebrow">Inline evidence · {event.displayName}</span><h2>{transition.previousResolvedOrder ?? 'Unknown'} → {transition.finalResolvedOrder ?? 'Unknown'}</h2></div><button type="button" onClick={onClose}>Close</button></div>
    <div className="co-inspector-facts"><span><small>Physical envelope</small><strong>{time(event.physical.physicalStartUtc)} → {time(event.physical.physicalRecoveryUtc)}</strong></span><span><small>Duration</small><strong>{duration(event.physical.durationSeconds)}</strong></span><span><small>Evidence</small><strong>{evidenceLabel(event.evidenceState)}</strong></span><span><small>Failed recoveries</small><strong>{event.physical.failedRecoveryAttempts.length}</strong></span></div>
    <SpeedChart inspector={value}/><EvidenceTrack inspector={value}/>
    <div className="co-inspector-grid"><article><h3>Asynchronous Order transition</h3><p><span>First next-job indication</span><strong>{time(transition.identityChangeFirstSeenAtUtc)}</strong></p><p><span>Final Order field change</span><strong>{time(transition.identityLastChangeAtUtc)}</strong></p><p><span>Identity settled / confirmed</span><strong>{time(transition.identitySettledAtUtc)}</strong></p><small>First-seen is an inferred metadata boundary, not unquestioned physical ground truth.</small></article><article><h3>Radius annotation alignment</h3><p><span>Annotation start lag</span><strong>{duration(event.radius?.annotationStartLagSeconds ?? null)}</strong></p><p><span>Annotation end lag</span><strong>{duration(event.radius?.annotationEndLagSeconds ?? null)}</strong></p><p><span>Reconciliation difference</span><strong>{duration(event.radius?.differenceSeconds ?? null)}</strong></p><small>Positive means Radius recorded the boundary later than physical behavior; negative means earlier. Radius never changes the physical envelope.</small></article></div>
    <div className="co-reason-table"><h3>Exact Radius detail</h3>{event.radius?.adjustedContributions.map((item, index) => { const raw = item.rawIntervalIndex === null ? undefined : event.radius?.rawIntervals[item.rawIntervalIndex]; return <div key={index}><span className={`co-phase-dot co-phase--${item.phase}`}/><strong>{item.identity.eventType ?? '—'} / {item.identity.statusCode ?? '—'}</strong><span>{item.identity.statusDescription ?? phaseLabel(item.phase)}</span><b>{duration(item.durationSeconds)}</b><small>{raw ? `Raw ${time(raw.originalStartUtc)} → ${time(raw.originalEndUtc)} (${duration(raw.originalDurationSeconds)}). ` : ''}Adjusted {time(item.adjustedStartUtc)} → {time(item.adjustedEndUtc)}. {item.reason}</small></div> }) ?? <p>Radius enrichment unavailable.</p>}</div>
  </section>
}

export function ChangeoverIntelligencePage({ selectedPress, onPressChange }: Props) {
  const initial = useMemo(() => { const query = new URLSearchParams(window.location.search); const preset = (query.get('range') ?? '7d') as Preset; return ['today', '24h', '7d', '30d', '90d', 'last', 'custom', 'all'].includes(preset) ? preset : '7d' }, [])
  const initialRange = useMemo(() => { const query = new URLSearchParams(window.location.search); const from = query.get('fromUtc'); const to = query.get('toUtc'); return initial === 'custom' && from && to && Number.isFinite(Date.parse(from)) && Number.isFinite(Date.parse(to)) && Date.parse(to) > Date.parse(from) ? { fromUtc: new Date(from).toISOString(), toUtc: new Date(to).toISOString() } : rangeFor(initial === 'custom' ? '7d' : initial) }, [initial])
  const [preset, setPreset] = useState<Preset>(initial); const [lastDays, setLastDays] = useState(14); const [range, setRange] = useState(initialRange); const [customFrom, setCustomFrom] = useState(initialRange.fromUtc.slice(0, 16)); const [customTo, setCustomTo] = useState(initialRange.toUtc.slice(0, 16))
  const [mode, setMode] = useState<ChangeoverMode>('CHANGEOVERS'); const [stopSpeed, setStopSpeed] = useState(DEFAULTS.stopSpeed); const [recoverySpeed, setRecoverySpeed] = useState(DEFAULTS.recoverySpeed); const [confirmation, setConfirmation] = useState(DEFAULTS.recoveryConfirmationSeconds)
  const [report, setReport] = useState<ChangeoverReport>(); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>(); const [inspector, setInspector] = useState<ChangeoverInspector>(); const [inspectorLoading, setInspectorLoading] = useState(false); const [reasonKey, setReasonKey] = useState<string>()
  const request: ChangeoverRequest = useMemo(() => ({ ...range, mode, focusPressKey: selectedPress ?? null, stopSpeed, recoverySpeed, recoveryConfirmationSeconds: confirmation }), [range, mode, selectedPress, stopSpeed, recoverySpeed, confirmation])

  useEffect(() => { let active = true; const controller = new AbortController(); setLoading(true); setError(undefined); void getChangeoverIntelligenceReport(request, controller.signal).then((value) => active && setReport(value)).catch((cause) => { if (active && (cause as Error).name !== 'AbortError') setError('Changeover evidence could not be loaded.') }).finally(() => active && setLoading(false)); return () => { active = false; controller.abort() } }, [request])
  useEffect(() => { const url = new URL(window.location.href); url.searchParams.set('range', preset); if (preset === 'custom') { url.searchParams.set('fromUtc', range.fromUtc); url.searchParams.set('toUtc', range.toUtc) } else { url.searchParams.delete('fromUtc'); url.searchParams.delete('toUtc') }; if (selectedPress) url.searchParams.set('press', selectedPress); else url.searchParams.delete('press'); window.history.replaceState({}, '', `${url.pathname}?${url.searchParams}`) }, [preset, range, selectedPress])

  function choosePreset(next: Preset) { setPreset(next); if (next !== 'custom') { setRange(rangeFor(next, lastDays)); setInspector(undefined) } }
  function applyCustom() { const from = new Date(customFrom); const to = new Date(customTo); if (Number.isFinite(from.getTime()) && Number.isFinite(to.getTime()) && to > from) { setPreset('custom'); setRange({ fromUtc: from.toISOString(), toUtc: to.toISOString() }); setInspector(undefined) } }
  function resetDefinition() { setStopSpeed(DEFAULTS.stopSpeed); setRecoverySpeed(DEFAULTS.recoverySpeed); setConfirmation(DEFAULTS.recoveryConfirmationSeconds) }
  function inspect(event: ChangeoverEvent) { if (!event.physical.physicalRecoveryUtc) return; setInspectorLoading(true); setInspector(undefined); void getChangeoverInspector({ ...request, changeoverId: event.changeoverId, pressKey: event.pressKey, physicalStartUtc: event.physical.physicalStartUtc, physicalRecoveryUtc: event.physical.physicalRecoveryUtc }).then((value) => { setInspector(value); window.setTimeout(() => document.getElementById('changeover-inspector')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 0) }).catch(() => setError('The selected bounded evidence window could not be reconstructed.')).finally(() => setInspectorLoading(false)) }
  const events = report ? (mode === 'CHANGEOVERS' ? report.changeovers : report.allStops) : []
  const custom = stopSpeed !== DEFAULTS.stopSpeed || recoverySpeed !== DEFAULTS.recoverySpeed || confirmation !== DEFAULTS.recoveryConfirmationSeconds
  const maximumPhase = Math.max(1, ...(report?.phases.map((item) => item.durationSeconds) ?? [])); const maximumDay = Math.max(1, ...(report?.daily.map((item) => item.durationSeconds) ?? []))
  const totalChangeoverSeconds = report?.changeovers.reduce((sum, item) => sum + (item.physical.durationSeconds ?? 0), 0) ?? 0; const totalStopSeconds = report?.allStops.reduce((sum, item) => sum + (item.physical.durationSeconds ?? 0), 0) ?? 0
  const failedChangeovers = report?.changeovers.filter((item) => item.physical.failedRecoveryAttempts.length > 0).length ?? 0; const loopChangeovers = report?.changeovers.filter((item) => item.phaseSequence.length > new Set(item.phaseSequence).size).length ?? 0
  const bestSupportedPress = report?.fleet.filter((item) => item.support.level === 'moderate' || item.support.level === 'strong').sort((left, right) => (left.duration.median ?? Infinity) - (right.duration.median ?? Infinity))[0]
  const largestPhase = report?.phases[0]; const maximumPressPhase = Math.max(1, ...(report?.fleet.flatMap((press) => press.phaseMinutesPerChangeover.map((item) => item.minutes)) ?? []))
  const sequenceCount = report?.sequences.reduce((sum, item) => sum + item.count, 0) ?? 0; const commonSequenceCount = report?.sequences[0]?.count ?? 0; const topThreeSequenceCount = report?.sequences.slice(0, 3).reduce((sum, item) => sum + item.count, 0) ?? 0; const uncommonSequenceCount = report?.sequences.filter((item) => item.count === 1).reduce((sum, item) => sum + item.count, 0) ?? 0
  const loopMedian = medianValue(report?.changeovers.filter((item) => item.phaseSequence.length > new Set(item.phaseSequence).size).flatMap((item) => item.physical.durationSeconds === null ? [] : [item.physical.durationSeconds]) ?? []); const noLoopMedian = medianValue(report?.changeovers.filter((item) => item.phaseSequence.length === new Set(item.phaseSequence).size).flatMap((item) => item.physical.durationSeconds === null ? [] : [item.physical.durationSeconds]) ?? [])

  return <div className="co-page">
    <section className="co-hero"><div><span className="eyebrow">Fleet-first deterministic analysis</span><h1>Changeover Intelligence</h1><p>Physical production behavior defines each envelope. Settled Order metadata confirms a job transition. Radius explains where the physical time went.</p></div><span className={`co-definition-badge ${custom ? 'custom' : ''}`}>{custom ? 'CUSTOM DEFINITION' : 'DEFAULT DEFINITION'}</span></section>
    <section className="co-controls" aria-label="Changeover analysis controls"><label>View<select value={mode} onChange={(event) => setMode(event.target.value as ChangeoverMode)}><option value="CHANGEOVERS">Changeovers</option><option value="ALL_STOPS">All stops (context)</option></select></label><div className="co-preset"><span>History</span>{(['today', '24h', '7d', '30d', '90d', 'all'] as Preset[]).map((item) => <button type="button" className={preset === item ? 'active' : ''} onClick={() => choosePreset(item)} key={item}>{item === 'all' ? 'All available' : item}</button>)}<label>Last <input type="number" min="1" max="3650" value={lastDays} onChange={(event) => setLastDays(Number(event.target.value))}/><button type="button" onClick={() => choosePreset('last')}>days</button></label></div><div className="co-custom-range"><input aria-label="Custom start" type="datetime-local" value={customFrom} onChange={(event) => setCustomFrom(event.target.value)}/><span>to</span><input aria-label="Custom end" type="datetime-local" value={customTo} onChange={(event) => setCustomTo(event.target.value)}/><button type="button" onClick={applyCustom}>Apply</button></div></section>
    <details className="panel co-definition"><summary>Changeover definition · Speed &lt; {stopSpeed}; recovery &gt; {recoverySpeed} sustained {confirmation / 60} min</summary><div><label>Stop below<input type="number" min="0" max="100" step="0.1" value={stopSpeed} onChange={(event) => setStopSpeed(Number(event.target.value))}/></label><label>Recovery above<input type="number" min="1" max="10000" value={recoverySpeed} onChange={(event) => setRecoverySpeed(Number(event.target.value))}/></label><label>Confirmation seconds<input type="number" min="30" max="1800" value={confirmation} onChange={(event) => setConfirmation(Number(event.target.value))}/></label><button type="button" onClick={resetDefinition}>Restore defaults</button></div><p>A confirmed stop is backdated to its first qualifying below-threshold sample. Recovery is measured to the first above-threshold sample that later sustains confirmation. Exact threshold values do not qualify.</p></details>
    {report?.historyState === 'LIMITED_HISTORY' && <div className="co-notice" role="status"><strong>LIMITED HISTORY</strong> {report.historyMessage}</div>}
    {error && <div className="co-notice co-notice--error" role="alert">{error}</div>}{loading && <div className="co-loading" role="status">Loading sequential fleet evidence…</div>}
    {report && <>
      <section className="co-summary-grid" aria-label="Fleet changeover summary"><article><small>Confirmed changeovers</small><strong>{report.changeovers.length}</strong><span>{report.allStops.length} physical stops · {report.allStops.filter((item) => item.classification === 'AMBIGUOUS_STOP').length} ambiguous</span></article><article><small>Total physical changeover</small><strong>{duration(totalChangeoverSeconds)}</strong><span>{totalStopSeconds ? Math.round(totalChangeoverSeconds / totalStopSeconds * 1_000) / 10 : 0}% of measured physical stop time</span></article><article><small>Fleet typical / tail</small><strong>{duration(report.duration.median)}</strong><span>P90 {duration(report.duration.p90)} · IQR {duration(report.duration.iqr)}</span></article><article><small>Best supported press</small><strong>{bestSupportedPress?.displayName ?? 'Insufficient comparable N'}</strong><span>{bestSupportedPress ? `${duration(bestSupportedPress.duration.median)} median · N=${bestSupportedPress.changeoverCount}` : 'No press has moderate support yet.'}</span></article><article><small>Largest phase</small><strong>{largestPhase ? phaseLabel(largestPhase.phase) : 'Unavailable'}</strong><span>{largestPhase ? `${duration(largestPhase.durationSeconds)} · ${largestPhase.percentOfPhysicalChangeover}%` : 'Radius explanation unavailable'}</span></article><article><small>Failed recovery rate</small><strong>{report.changeovers.length ? Math.round(failedChangeovers / report.changeovers.length * 1_000) / 10 : 0}%</strong><span>{failedChangeovers} of {report.changeovers.length} changeovers</span></article><article><small>Loop / rework association</small><strong>{report.changeovers.length ? Math.round(loopChangeovers / report.changeovers.length * 1_000) / 10 : 0}%</strong><span>{loopChangeovers} observed phase loops</span></article></section>
      <section className="co-fleet-grid" aria-label="Fleet changeover cards">{report.fleet.map((press) => <button key={press.pressKey} type="button" className={`co-fleet-card ${press.focused ? 'focused' : ''}`} onClick={() => onPressChange(press.focused ? undefined : press.pressKey)}><header><strong>{press.displayName}</strong><span>{evidenceLabel(press.evidenceState)}</span></header><b>{duration(press.duration.median)}</b><small>median physical changeover · {press.changeoverCount} confirmed</small><div><span>P90 {duration(press.duration.p90)}</span><span>{press.failedRecoveryAttemptCount} failed recoveries</span></div></button>)}</section>
      <section className="panel"><div className="section-heading"><div><span className="eyebrow">All-press performance board</span><h2>Physical changeover distributions by press</h2></div><Support level={report.support.level} count={report.support.count}/></div><div className="co-table"><table><thead><tr><th>Press</th><th>N / total</th><th>Median / P25 / P75 / P90</th><th>IQR</th><th>Failed recovery</th><th>Annotation lag start / end</th><th>Radius coverage</th><th>Support</th></tr></thead><tbody>{report.fleet.map((press) => <tr key={press.pressKey} className={press.focused ? 'focused' : ''} onClick={() => onPressChange(press.focused ? undefined : press.pressKey)} tabIndex={0}><td><strong>{press.displayName}</strong><small>{press.otherStopCount} other · {press.ambiguousStopCount} ambiguous</small></td><td>{press.changeoverCount}<small>{duration(press.totalChangeoverSeconds)} total</small></td><td>{duration(press.duration.median)}<small>{duration(press.duration.p25)} / {duration(press.duration.p75)} / {duration(press.duration.p90)}</small></td><td>{duration(press.duration.iqr)}</td><td>{press.failedRecoveriesPerChangeover ?? '—'} / event<small>{press.percentWithFailedRecovery ?? '—'}% with ≥1 · 0/1/2+ counts {([0, 1, 2] as const).map((band) => report.changeovers.filter((item) => item.pressKey === press.pressKey && (band < 2 ? item.physical.failedRecoveryAttempts.length === band : item.physical.failedRecoveryAttempts.length >= 2)).length).join('/')}</small></td><td>{duration(press.annotationStartLag.median)} / {duration(press.annotationEndLag.median)}</td><td>{press.radiusCoveragePercent ?? '—'}%</td><td><Support level={press.support.level} count={press.support.count}/></td></tr>)}</tbody></table></div></section>
      <section className="panel"><div className="section-heading"><div><span className="eyebrow">Inline historical evidence</span><h2>{mode === 'CHANGEOVERS' ? 'Confirmed physical changeovers' : 'All physical stops (context)'}</h2></div></div><div className="co-table"><table><thead><tr><th>Press</th><th>Previous → current Order</th><th>Physical window</th><th>Recorded sequence</th><th>Failed recovery</th><th>Evidence</th></tr></thead><tbody>{events.map((event) => <tr key={event.changeoverId} className={event.pressKey === selectedPress ? 'focused' : ''} onClick={() => inspect(event)} tabIndex={0}><td>{event.displayName}</td><td><strong>{event.orderTransition.previousResolvedOrder ?? 'Unknown'} → {event.orderTransition.finalResolvedOrder ?? 'Unknown'}</strong><small>{evidenceLabel(event.classification)}</small></td><td>{duration(event.physical.durationSeconds)}<small>{time(event.physical.physicalStartUtc)}</small></td><td>{event.radius ? `${event.phaseSequence.map(phaseLabel).join(' → ')}` : 'Radius unavailable'}</td><td>{event.physical.failedRecoveryAttempts.length}</td><td><span className={`co-state co-state--${event.evidenceState.toLowerCase()}`}>{evidenceLabel(event.evidenceState)}</span></td></tr>)}</tbody></table>{!events.length && <p className="empty-state">No events meet the selected deterministic definition in the analyzed interval.</p>}</div></section>
      <div className="co-two-column"><section className="panel"><div className="section-heading"><div><span className="eyebrow">Where changeover time goes</span><h2>Adjusted physical-window phases</h2></div><Distribution value={report.duration}/></div><div className="co-bars">{report.phases.map((item) => <div key={item.phase}><label><strong>{phaseLabel(item.phase)}</strong><span>{duration(item.durationSeconds)} · {item.percentOfPhysicalChangeover}%</span></label><i><b className={`co-phase--${item.phase}`} style={{ width: `${item.durationSeconds / maximumPhase * 100}%` }}/></i></div>)}</div><h3 className="co-subheading">Minutes per changeover by press</h3><div className="co-phase-matrix">{report.fleet.map((press) => <article key={press.pressKey}><strong>{press.displayName}</strong><div>{press.phaseMinutesPerChangeover.map((item) => <span key={item.phase} title={`${phaseLabel(item.phase)}: ${item.minutes} min/changeover`}><i className={`co-phase--${item.phase}`} style={{ width: `${item.minutes / maximumPressPhase * 100}%` }}/><small>{phaseLabel(item.phase)} {item.minutes}</small></span>)}</div></article>)}</div></section><section className="panel"><div className="section-heading"><div><span className="eyebrow">Exact evidence</span><h2>Radius loss reasons</h2></div></div><div className="co-exact-list">{report.exactReasons.slice(0, 10).map((item) => { const key = JSON.stringify(item.identity); return <button type="button" key={`${item.phase}-${key}`} onClick={() => setReasonKey(reasonKey === key ? undefined : key)}><span className={`co-phase-dot co-phase--${item.phase}`}/><strong>{item.identity.eventType ?? '—'} / {item.identity.statusCode ?? '—'}</strong><span>{item.identity.statusDescription ?? phaseLabel(item.phase)}</span><b>{item.minutesPerChangeover} min/changeover</b>{reasonKey === key && <small>{duration(item.durationSeconds)} total · {item.occurrenceCount} occurrences · {item.changeoverCount} affected changeovers · median occurrence {duration(item.medianOccurrenceSeconds)}. {item.support.description}</small>}</button> })}</div></section></div>
      <div className="co-two-column"><section className="panel"><div className="section-heading"><div><span className="eyebrow">Failed recovery & sequence</span><h2>Typical historical sequences</h2></div></div><div className="co-recovery-cohorts">{report.recoveryCohorts.map((item) => <article key={item.attemptBand}><small>{item.attemptBand === 'multiple' ? 'Multiple attempts' : `${item.attemptBand} failed attempts`}</small><strong>{duration(item.duration.median)}</strong><span>{item.changeoverCount} changeovers · {item.percentOfChangeovers}%</span><Support level={item.support.level} count={item.changeoverCount}/></article>)}</div><p className="co-caveat">Association only: changeovers with failed attempts may be longer; this analysis does not claim causation.</p><div className="co-conformance"><span><small>Most common</small><strong>{sequenceCount ? Math.round(commonSequenceCount / sequenceCount * 1_000) / 10 : 0}%</strong></span><span><small>Top 3 patterns</small><strong>{sequenceCount ? Math.round(topThreeSequenceCount / sequenceCount * 1_000) / 10 : 0}%</strong></span><span><small>Uncommon (N=1)</small><strong>{sequenceCount ? Math.round(uncommonSequenceCount / sequenceCount * 1_000) / 10 : 0}%</strong></span><span><small>Loop vs no loop median</small><strong>{duration(loopMedian)} / {duration(noLoopMedian)}</strong></span></div><div className="co-sequences">{report.sequences.slice(0, 8).map((item, index) => <article key={index}><strong>{item.sequence.map(phaseLabel).join(' → ')}</strong><span>{item.count} events · {sequenceCount ? Math.round(item.count / sequenceCount * 1_000) / 10 : 0}% · median {duration(item.duration.median)}</span><small>{item.failedRecoveryAttemptCount} failed recovery attempts · {item.loopCount} loops</small><Support level={item.support.level} count={item.support.count}/></article>)}</div></section><section className="panel"><div className="section-heading"><div><span className="eyebrow">Order-to-Order transitions</span><h2>Transition pairs</h2></div></div><div className="co-pairs">{report.transitionPairs.slice(0, 10).map((item) => <article key={`${item.previousOrder}-${item.currentOrder}`}><strong>{item.previousOrder} → {item.currentOrder}</strong><Distribution value={item.duration}/><small>{item.presses.map((press) => press.replace('press', 'P')).join(', ')} · {item.failedRecoveryPercent}% failed recovery · {item.dominantSequence.map(phaseLabel).join(' → ') || 'No Radius sequence'}</small><small>{item.phaseMinutesPerChangeover.slice(0, 3).map((phase) => `${phaseLabel(phase.phase)} ${phase.minutes}m`).join(' · ')}</small><Support level={item.support.level} count={item.count}/></article>)}</div>{report.transitionPairs.every((item) => item.count < 3) && <p className="co-caveat">Tiny-N pairs are shown as observations only; no “best” claim is made.</p>}</section></div>
      <section className="panel"><div className="section-heading"><div><span className="eyebrow">Trends and zero-day visibility</span><h2>Daily physical changeover timeline</h2></div><span>{report.daily.length} calendar days</span></div><div className="co-daily" aria-label="Daily changeover duration">{report.daily.map((item) => <div key={item.date} title={`${item.date}: ${item.count} changeovers, ${duration(item.durationSeconds)}`}><i style={{ height: `${Math.max(item.count ? 4 : 1, item.durationSeconds / maximumDay * 100)}%` }}/><small>{item.date.slice(5)}</small><b>{item.count}</b></div>)}</div><div className="co-daily-detail">{report.daily.map((day) => { const dayEvents = events.filter((event) => localDateKey(event.physical.physicalStartUtc) === day.date).sort((left, right) => Date.parse(left.physical.physicalStartUtc) - Date.parse(right.physical.physicalStartUtc)); return <article key={day.date}><header><div><strong>{day.date}</strong><span>{day.count} {mode === 'CHANGEOVERS' ? 'changeovers' : 'stops'} · total {duration(day.durationSeconds)} · median {duration(day.medianDurationSeconds)}</span></div><b>{day.failedRecoveryAttemptCount} failed recoveries</b></header>{dayEvents.length ? dayEvents.map((event) => <button type="button" key={event.changeoverId} className={selectedPress && event.pressKey !== selectedPress ? 'deemphasized' : ''} onClick={() => inspect(event)}><strong>{event.displayName}</strong><span>{event.orderTransition.previousResolvedOrder ?? 'Unknown'} → {event.orderTransition.finalResolvedOrder ?? 'Unknown'}</span><span>{time(event.physical.physicalStartUtc)} → {time(event.physical.physicalRecoveryUtc)}</span><b>{duration(event.physical.durationSeconds)} · {event.physical.failedRecoveryAttempts.length} failed</b><i>{event.radius?.adjustedContributions.map((phase, index) => <em key={index} className={`co-phase--${phase.phase}`} style={{ width: `${phase.durationSeconds / Math.max(1, event.physical.durationSeconds ?? 1) * 100}%` }}/>)}</i></button>) : <p>0 {mode === 'CHANGEOVERS' ? 'changeovers' : 'stops'}</p>}</article> })}</div><div className="co-metadata-only">{report.metadataOnlyTransitions.length} Order identity transitions had no associated physical stop and are tracked separately—not counted as changeovers.</div></section>
      <Inspector value={inspector} loading={inspectorLoading} onClose={() => setInspector(undefined)}/>
      <details className="panel co-method"><summary>Evidence rules, uncertainty, and source boundaries</summary><p>Canonical actual-speed telemetry owns physical start and recovery. Order changes are coalesced for five minutes and retain first-seen, last-change, and settled timestamps. A changeover requires different stable Orders before and after the physical stop. Radius original timestamps are preserved, then clipped into an adjusted track whose durations reconcile exactly to the physical envelope. Gaps, unknown time, and Radius/telemetry mismatches remain explicit. Version {report.algorithmVersion}; {report.diagnostics.sequentialRadiusAcquisitions} sequential Radius acquisitions; cache {report.diagnostics.cache}.</p></details>
    </>}
  </div>
}
