import { useEffect, useMemo, useState } from 'react'
import { getJobIntelligenceReport, getJobIntelligenceRun, getJobIntelligenceValues } from '../api/process-intelligence-api'
import type { FleetJobIntelligenceReport, FleetRadiusLossComparison, HistoricalRunSort, HistoricalRunSummary, JobAnalysisDimension, JobEvidenceLevel, JobGroupDefinition, JobGroupOperator, JobIntelligenceValues, JobRefinement, JobRunInspector, RadiusPressKey } from '../types/api'

const presses: RadiusPressKey[] = ['press3', 'press5', 'press6', 'press7', 'press8', 'press9', 'press10', 'press11', 'press12', 'press13', 'press14', 'press15']
const dimensions: Array<{ value: JobAnalysisDimension; label: string }> = [{ value: 'order', label: 'Order' }, { value: 'recipe', label: 'Recipe' }, { value: 'customer', label: 'Customer' }, { value: 'material', label: 'Material' }]
const operatorLabels: Record<JobGroupOperator, string> = { exact: 'Exact match', contains: 'Contains', starts_with: 'Starts with', ends_with: 'Ends with', position_range: 'Position / range', segment_equals: 'Segment equals' }
type HistoryPreset = '7' | '30' | '90' | 'all'

interface Props { selectedPress?: RadiusPressKey; onPressChange(pressKey: RadiusPressKey | undefined): void }
const formatDuration = (seconds: number | null) => seconds === null ? '—' : seconds >= 3600 ? `${Math.round(seconds / 360) / 10} h` : seconds >= 60 ? `${Math.round(seconds / 6) / 10} min` : `${Math.round(seconds)} sec`
const formatNumber = (value: number | null, suffix = '') => value === null ? '—' : `${Math.round(value * 10) / 10}${suffix}`
const supportLabel = (level: JobEvidenceLevel) => level[0]!.toUpperCase() + level.slice(1)
const pressLabel = (press: RadiusPressKey) => press.replace('press', 'Press ')
const localTime = (value: string | null) => value ? new Intl.DateTimeFormat('en-US', { timeZone: 'America/Chicago', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value)) : '—'
const consistencyLabel = (variability: number | null) => variability === null ? 'Insufficient history' : variability <= 10 ? 'Consistent' : variability <= 25 ? 'Variable' : 'Highly variable'

function groupFromLocation(): JobGroupDefinition | undefined {
  const parameters = new URLSearchParams(window.location.search); const operator = parameters.get('operator') as JobGroupOperator | null; const value = parameters.get('query')
  if (!operator || !value || !(operator in operatorLabels)) return undefined
  const integer = (name: string) => { const parsed = Number(parameters.get(name)); return Number.isSafeInteger(parsed) && parsed > 0 ? parsed : undefined }
  return { operator, query: value, positionStart: integer('positionStart'), positionEnd: integer('positionEnd'), segmentIndex: integer('segmentIndex'), delimiter: parameters.get('delimiter') ?? undefined }
}

function presetFromLocation(): HistoryPreset { const value = new URLSearchParams(window.location.search).get('history'); return value === '7' || value === '30' || value === '90' || value === 'all' ? value : '30' }
function refinementsFromLocation(): JobRefinement[] {
  const value = new URLSearchParams(window.location.search).get('refinements'); if (!value || value.length > 5_000) return []
  try { const parsed = JSON.parse(value) as unknown; if (!Array.isArray(parsed) || parsed.length > 5) return []; return parsed.filter((item): item is JobRefinement => Boolean(item && typeof item === 'object' && dimensions.some((dimension) => dimension.value === (item as JobRefinement).dimension) && (item as JobRefinement).group && typeof (item as JobRefinement).group.query === 'string' && (item as JobRefinement).group.query.length <= 240 && (item as JobRefinement).group.operator in operatorLabels)) } catch { return [] }
}

function historyRange(preset: HistoryPreset) {
  const to = new Date(); const from = new Date(to)
  if (preset === 'all') from.setUTCFullYear(from.getUTCFullYear() - 10)
  else from.setUTCDate(from.getUTCDate() - Number(preset))
  return { fromUtc: from.toISOString(), toUtc: to.toISOString() }
}

function StateBar({ good, makeReady, bad, unavailable = 0 }: { good: number; makeReady: number; bad: number; unavailable?: number }) {
  return <div className="ji-state-bar" aria-label={`${good}% Good, ${makeReady}% Make Ready, ${bad}% Bad, ${unavailable}% unavailable`}><span className="ji-state-good" style={{ width: `${good}%` }} /><span className="ji-state-make-ready" style={{ width: `${makeReady}%` }} /><span className="ji-state-bad" style={{ width: `${bad}%` }} /><span className="ji-state-unavailable" style={{ width: `${unavailable}%` }} /></div>
}

function RunInspector({ inspector, loading, onClose }: { inspector?: JobRunInspector; loading: boolean; onClose(): void }) {
  if (loading) return <section className="panel ji-inspector" id="run-inspector" role="status">Loading run evidence…</section>
  if (!inspector) return null
  const run = inspector.run; const transition = run.identityTransition; const timing = run.transitionTiming; const currentIdentities = transition.finalResolvedIdentity; const previousIdentities = transition.previousResolvedIdentity ?? run.previousIdentities; const currentJob = currentIdentities.order ?? currentIdentities.recipe ?? 'Current job'; const previousJob = previousIdentities?.order ?? previousIdentities?.recipe ?? 'Unavailable'
  return <section className="panel ji-inspector" id="run-inspector" aria-labelledby="run-inspector-title">
    <div className="section-heading"><div><span className="eyebrow">Inline run evidence · {pressLabel(run.pressKey)}</span><h2 id="run-inspector-title">{run.identities.order ?? run.identities.recipe ?? run.runId}</h2></div><button type="button" className="ji-close" onClick={onClose}>Close</button></div>
    <div className="ji-inspector-facts"><span><small>Press</small><strong>{pressLabel(run.pressKey)}</strong></span><span><small>Run window</small><strong>{localTime(run.startUtc)} – {localTime(run.endUtc)}</strong></span><span><small>Support</small><strong>{supportLabel(inspector.support.level)} · N={inspector.support.runCount}</strong></span><span><small>Confidence</small><strong>{run.identityConfidence}{run.dataInterrupted ? ' · data gap' : ''}</strong></span></div>
    <div className="ji-inspector-grid">
      <article><h3>Resolved identity</h3>{dimensions.map(({ value, label }) => <p key={value}><span>{label}</span><strong>{currentIdentities[value] ?? 'Unavailable'}</strong><small>Previous resolved: {previousIdentities?.[value] ?? 'Unavailable'}</small></p>)}</article>
      <article><h3>Performance</h3><p><span>Good / Make Ready / Bad</span><strong>{run.goodPercent}% / {run.makeReadyPercent}% / {run.badPercent}%</strong><StateBar good={run.goodPercent} makeReady={run.makeReadyPercent} bad={run.badPercent} unavailable={run.unavailablePercent} /></p><p><span>Transition time</span><strong>{formatDuration(run.transitionSeconds)}</strong></p><p><span>Interruptions</span><strong>{run.interruptions}</strong></p><p><span>Median running speed</span><strong>{formatNumber(run.medianRunningSpeed, run.runningSpeedUnit ? ` ${run.runningSpeedUnit}` : '')}</strong></p></article>
      <article><h3>Transition context</h3><p><span>Previous → current</span><strong>{previousJob} → {currentJob}</strong></p><p><span>First metadata indication</span><strong>{localTime(transition.identityChangeFirstSeenAtUtc)}</strong><small>{transition.inferredBoundary ? 'Inferred segmentation boundary; identity was still settling.' : transition.settleState}</small></p><p><span>Completed metadata transition</span><strong>{localTime(transition.identityLastChangeAtUtc)}</strong><small>Settled / confirmed {localTime(transition.identitySettledAtUtc)}</small></p><p><span>Radius stable production</span><strong>{localTime(timing.incomingStableRadiusProductionStartUtc)}</strong><small>{timing.timingUncertaintySeconds === null ? 'Timing uncertainty unavailable' : `${formatDuration(timing.timingUncertaintySeconds)} metadata settling uncertainty`}</small></p><p><span>Telemetry physical behavior</span><strong>{localTime(timing.telemetryPhysicalProductionAtUtc)}</strong><small>{timing.telemetryPhysicalProductionAtUtc ? 'Telemetry-derived physical production indication' : 'Not inferred in summary evidence'}</small></p><p><span>Decks reused / added / removed</span><strong>{run.deckConfiguration ? `${run.deckConfiguration.reusedDecks.join(', ') || 'none'} / ${run.deckConfiguration.addedDecks.join(', ') || 'none'} / ${run.deckConfiguration.removedDecks.join(', ') || 'none'}` : 'Unavailable'}</strong></p></article>
    </div>
    <h3>Main Radius losses</h3>{run.mainRadiusLosses.length ? <div className="ji-inline-table"><table><thead><tr><th>Type / code</th><th>Reason</th><th>Total</th><th>Occurrences</th><th>Median occurrence</th></tr></thead><tbody>{run.mainRadiusLosses.map((loss) => <tr key={`${loss.eventType}-${loss.statusCode}-${loss.statusDescription}`}><td><span className={`ji-radius-code ji-radius-code--${loss.eventType.toLowerCase()}`}>{loss.eventType}</span> / {loss.statusCode ?? '—'}</td><td>{loss.statusDescription}</td><td>{formatDuration(loss.totalSeconds)}</td><td>{loss.occurrenceCount}</td><td>{formatDuration(loss.medianEpisodeSeconds)}</td></tr>)}</tbody></table></div> : <p className="empty-state">No Make Ready or Bad loss reason was recorded for this run.</p>}
  </section>
}

export function JobIntelligencePage({ selectedPress, onPressChange }: Props) {
  const initialGroup = useMemo(groupFromLocation, [])
  const initialPreset = useMemo(presetFromLocation, []); const initialRefinements = useMemo(refinementsFromLocation, []); const initialRunId = useMemo(() => new URLSearchParams(window.location.search).get('run'), [])
  const [preset, setPreset] = useState<HistoryPreset>(initialPreset); const [range, setRange] = useState(() => historyRange(initialPreset))
  const [analyzeBy, setAnalyzeBy] = useState<JobAnalysisDimension>(() => { const value = new URLSearchParams(window.location.search).get('analyzeBy'); return dimensions.some((item) => item.value === value) ? value as JobAnalysisDimension : 'recipe' })
  const [operator, setOperator] = useState<JobGroupOperator>(initialGroup?.operator ?? 'exact'); const [query, setQuery] = useState(initialGroup?.query ?? '')
  const [positionStart, setPositionStart] = useState(initialGroup?.positionStart ?? 1); const [positionEnd, setPositionEnd] = useState(initialGroup?.positionEnd ?? 1); const [segmentIndex, setSegmentIndex] = useState(initialGroup?.segmentIndex ?? 3); const [delimiter, setDelimiter] = useState(initialGroup?.delimiter ?? '-')
  const [appliedGroup, setAppliedGroup] = useState<JobGroupDefinition | undefined>(initialGroup); const [refinements, setRefinements] = useState<JobRefinement[]>(initialRefinements)
  const [refinementDimension, setRefinementDimension] = useState<JobAnalysisDimension>('material'); const [refinementOperator, setRefinementOperator] = useState<JobGroupOperator>('exact'); const [refinementValue, setRefinementValue] = useState(''); const [refinementPrevious, setRefinementPrevious] = useState(false)
  const [valueQuery, setValueQuery] = useState(''); const [values, setValues] = useState<JobIntelligenceValues>(); const [valuesLoading, setValuesLoading] = useState(true)
  const [report, setReport] = useState<FleetJobIntelligenceReport>(); const [loading, setLoading] = useState(false); const [error, setError] = useState<string>(); const [offset, setOffset] = useState(0)
  const [inspector, setInspector] = useState<JobRunInspector>(); const [inspectorLoading, setInspectorLoading] = useState(false)
  const [selectedLoss, setSelectedLoss] = useState<FleetRadiusLossComparison>(); const [historySort, setHistorySort] = useState<HistoricalRunSort>('newest'); const [pressSort, setPressSort] = useState<'affinity' | 'good' | 'make_ready' | 'bad' | 'changeover' | 'stability' | 'speed' | 'opportunity'>('affinity')
  const focusPress = selectedPress ?? null

  useEffect(() => {
    let active = true; const controller = new AbortController(); const timer = window.setTimeout(() => {
      setValuesLoading(true)
      void getJobIntelligenceValues({ ...range, analyzeBy, query: valueQuery, limit: 60 }, controller.signal).then((next) => { if (!active) return; setValues(next); if (!valueQuery && next.values[0]) setAppliedGroup((current) => { if (current) return current; const group = { operator: 'exact' as const, query: next.values[0]!.value }; setQuery(group.query); return group }) }).catch(() => active && setError('Available identity values could not be loaded.')).finally(() => active && setValuesLoading(false))
    }, 180)
    return () => { active = false; window.clearTimeout(timer); controller.abort() }
  }, [range, analyzeBy, valueQuery])

  useEffect(() => {
    if (!appliedGroup) { setReport(undefined); return }
    let active = true; const controller = new AbortController(); setLoading(true); setError(undefined)
    void getJobIntelligenceReport({ ...range, analyzeBy, group: appliedGroup, refinements, focusPressKey: focusPress, offset, limit: 50, sort: historySort }, controller.signal).then((next) => active && setReport(next)).catch(() => active && setError('Job Intelligence evidence could not be loaded for this fleet selection.')).finally(() => active && setLoading(false))
    return () => { active = false; controller.abort() }
  }, [range, analyzeBy, appliedGroup, refinements, focusPress, offset, historySort])

  useEffect(() => {
    const url = new URL(window.location.href); url.searchParams.set('analyzeBy', analyzeBy); url.searchParams.set('history', preset)
    if (refinements.length) url.searchParams.set('refinements', JSON.stringify(refinements)); else url.searchParams.delete('refinements')
    window.history.replaceState({}, '', `${url.pathname}?${url.searchParams}`)
  }, [analyzeBy, preset, refinements])

  useEffect(() => { if (initialRunId && /^[A-Za-z0-9._-]{1,160}$/.test(initialRunId)) inspectRun({ runId: initialRunId }) }, [initialRunId])

  function persistSelection(group?: JobGroupDefinition, nextDimension = analyzeBy) { const url = new URL(window.location.href); url.searchParams.set('analyzeBy', nextDimension); for (const key of ['operator', 'query', 'positionStart', 'positionEnd', 'segmentIndex', 'delimiter']) url.searchParams.delete(key); if (group) { url.searchParams.set('operator', group.operator); url.searchParams.set('query', group.query) }; window.history.replaceState({}, '', `${url.pathname}?${url.searchParams}`) }
  function applyGroup(group: JobGroupDefinition) { setAppliedGroup(group); setOffset(0); setInspector(undefined); setSelectedLoss(undefined); persistSelection(group) }
  function applyDraft() { const value = query.trim(); if (!value) return; applyGroup({ operator, query: value, ...(operator === 'position_range' ? { positionStart, positionEnd } : {}), ...(operator === 'segment_equals' ? { segmentIndex, delimiter } : {}) }) }
  function changeDimension(value: JobAnalysisDimension) { setAnalyzeBy(value); setAppliedGroup(undefined); setQuery(''); setValueQuery(''); setRefinements([]); setRefinementDimension(dimensions.find((item) => item.value !== value)?.value ?? 'order'); setOffset(0); persistSelection(undefined, value) }
  function changePreset(value: HistoryPreset) { setPreset(value); setRange(historyRange(value)); setOffset(0); setInspector(undefined) }
  function addRefinement() { const value = refinementValue.trim(); if (!value || refinementDimension === analyzeBy || refinementOperator === 'position_range' || refinementOperator === 'segment_equals') return; setRefinements((items) => [...items.filter((item) => item.dimension !== refinementDimension || Boolean(item.previousIdentity) !== refinementPrevious), { dimension: refinementDimension, group: { operator: refinementOperator, query: value }, ...(refinementPrevious ? { previousIdentity: true } : {}) }]); setRefinementValue(''); setOffset(0) }
  function inspectRun(run: Pick<HistoricalRunSummary, 'runId'>) { setInspectorLoading(true); setInspector(undefined); void getJobIntelligenceRun(run.runId).then((value) => { setInspector(value); const url = new URL(window.location.href); url.searchParams.set('run', value.run.runId); window.history.replaceState({}, '', `${url.pathname}?${url.searchParams}`); window.setTimeout(() => document.getElementById('run-inspector')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 0) }).catch(() => setError('That run’s inline evidence could not be loaded.')).finally(() => setInspectorLoading(false)) }
  function decisionAnchor(anchor: string) { document.getElementById(anchor.replace(/^#/, ''))?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }
  const sortedPresses = useMemo(() => { const rows = [...(report?.presses ?? [])]; const value = (press: typeof rows[number]) => ({ affinity: press.actualVersusComparableGoodPoints ?? -Infinity, good: press.goodPercent, make_ready: -press.makeReadyPercent, bad: -press.badPercent, changeover: -(press.changeover.durationSeconds.median ?? Infinity), stability: -(press.running.interruptionsPerProductionHour ?? Infinity), speed: press.running.speed?.distribution.median ?? -Infinity, opportunity: press.recoverableOpportunitySeconds ?? -Infinity })[pressSort]; return rows.sort((left, right) => value(right) - value(left) || left.pressKey.localeCompare(right.pressKey)) }, [report, pressSort])
  const speedComparable = useMemo(() => { const evidence = (report?.presses ?? []).flatMap((press) => press.running.speed ? [press.running.speed] : []); return evidence.length > 1 && Boolean(evidence[0]?.sourceUnit) && evidence.every((item) => item.sourceUnit === evidence[0]!.sourceUnit && /verified|canonical/i.test(item.canonicalUnitStatus ?? '')) }, [report])

  return <div className="ji-page">
    <section className="ji-controls ji-controls--fleet" aria-label="Job Intelligence controls"><label><span>Analyze by</span><select value={analyzeBy} onChange={(event) => changeDimension(event.target.value as JobAnalysisDimension)}>{dimensions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label><span>Press focus (optional)</span><select value={focusPress ?? 'all'} onChange={(event) => onPressChange(event.target.value === 'all' ? undefined : event.target.value as RadiusPressKey)}><option value="all">All presses</option>{presses.map((press) => <option key={press} value={press}>{pressLabel(press)}</option>)}</select></label><div className="ji-history-presets"><span>History</span><div>{(['7', '30', '90', 'all'] as HistoryPreset[]).map((item) => <button type="button" key={item} className={preset === item ? 'active' : ''} onClick={() => changePreset(item)}>{item === 'all' ? 'All available' : `${item} days`}</button>)}</div></div></section>
    <section className="ji-group-builder panel" aria-labelledby="ji-group-title"><div><span className="eyebrow">Fleet identity selection</span><h1 id="ji-group-title">Job Intelligence</h1><small>Choose an identity first; every matching press is compared together.</small></div><div className="ji-group-fields"><select aria-label="Group match method" value={operator} onChange={(event) => setOperator(event.target.value as JobGroupOperator)}>{Object.entries(operatorLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>{operator === 'position_range' && <><input aria-label="Start position" type="number" min="1" max="240" value={positionStart} onChange={(event) => setPositionStart(Number(event.target.value))} /><input aria-label="End position" type="number" min="1" max="240" value={positionEnd} onChange={(event) => setPositionEnd(Number(event.target.value))} /></>}{operator === 'segment_equals' && <><input aria-label="Segment number" type="number" min="1" max="20" value={segmentIndex} onChange={(event) => setSegmentIndex(Number(event.target.value))} /><input aria-label="Delimiter" className="ji-delimiter" maxLength={3} value={delimiter} onChange={(event) => setDelimiter(event.target.value)} /></>}<input aria-label="Group value" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Select or group ${analyzeBy} values`} /><button type="button" onClick={applyDraft} disabled={!query.trim()}>Analyze fleet</button></div></section>
    <section className="panel ji-value-picker"><div className="section-heading"><div><span className="eyebrow">Available {analyzeBy} values</span><h2>Select a production identity</h2></div><input aria-label="Search available identities" value={valueQuery} onChange={(event) => setValueQuery(event.target.value)} placeholder="Search values" /></div>{valuesLoading && <small>Loading available values…</small>}<div className="ji-value-chips">{values?.values.map((item) => <button type="button" key={item.value} className={appliedGroup?.operator === 'exact' && appliedGroup.query === item.value ? 'selected' : ''} onClick={() => { setOperator('exact'); setQuery(item.value); applyGroup({ operator: 'exact', query: item.value }) }}><strong>{item.value}</strong><small>{item.runCount} runs · {item.pressKeys.length} presses</small></button>)}</div></section>
    <section className="panel ji-refinements"><div><span className="eyebrow">Optional refinements</span><strong>Filter the fleet cohort by another identity field.</strong></div><label className="ji-check"><input type="checkbox" checked={refinementPrevious} onChange={(event) => setRefinementPrevious(event.target.checked)} />Previous identity</label><select value={refinementDimension} onChange={(event) => setRefinementDimension(event.target.value as JobAnalysisDimension)}>{dimensions.filter((item) => item.value !== analyzeBy).map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><select value={refinementOperator} onChange={(event) => setRefinementOperator(event.target.value as JobGroupOperator)}>{(['exact', 'contains', 'starts_with', 'ends_with'] as JobGroupOperator[]).map((item) => <option key={item} value={item}>{operatorLabels[item]}</option>)}</select><input value={refinementValue} onChange={(event) => setRefinementValue(event.target.value)} placeholder="Value" aria-label="Refinement value" /><button type="button" disabled={!refinementValue.trim() || refinementDimension === analyzeBy} onClick={addRefinement}>Add filter</button><div className="ji-refinement-chips">{refinements.map((item, index) => <button type="button" key={`${item.dimension}-${index}`} onClick={() => { setRefinements((items) => items.filter((_value, itemIndex) => itemIndex !== index)); setOffset(0) }}>{item.previousIdentity ? 'previous ' : ''}{item.dimension} {item.group.operator.replaceAll('_', ' ')} {item.group.query} ×</button>)}</div></section>
    {loading && <div className="scope-progress" role="status"><i aria-hidden="true" />Building fleet history and live-tail evidence…</div>}{error && <section className="panel unavailable-panel" role="alert"><h2>Evidence unavailable</h2><p>{error}</p></section>}
    {report && <>
      <section className="ji-selection-summary"><article><small>Selection</small><strong>{report.selection.includedValues.length} value{report.selection.includedValues.length === 1 ? '' : 's'}</strong><span>{report.selection.includedValues.slice(0, 3).join(' · ') || 'No matches'}</span></article><article><small>Fleet coverage</small><strong>{report.fleetSummary.matchingPressCount} presses</strong><span>{report.selection.runCount} runs · {report.selection.observedHours} observed h</span></article><article><small>Production state</small><strong>{report.fleetSummary.goodPercent}% Good</strong><StateBar good={report.fleetSummary.goodPercent} makeReady={report.fleetSummary.makeReadyPercent} bad={report.fleetSummary.badPercent} unavailable={report.fleetSummary.unavailablePercent} /></article><article><small>Evidence support</small><strong>{supportLabel(report.fleetSummary.support.level)}</strong><span>{report.fleetSummary.support.reason}</span></article></section>
      <section className="ji-decision-grid" aria-label="Decisions">{report.decisions.map((card) => <article key={`${card.kind}-${card.headline}`} className={`ji-decision ji-support--${card.evidenceLevel}`}><span>{card.label}</span><h2>{card.headline}</h2><strong>{card.value}</strong><small>{card.detail}</small><button type="button" onClick={() => decisionAnchor(card.inspectUrl)}>Inspect inline evidence</button></article>)}</section>
      <section className="panel" id="all-press-performance"><div className="section-heading"><div><span className="eyebrow">Core fleet comparison</span><h2>How this selection runs across all presses</h2></div><div className="ji-section-controls"><label>Sort <select value={pressSort} onChange={(event) => setPressSort(event.target.value as typeof pressSort)}><option value="affinity">Best comparable result</option><option value="good">Best Good %</option><option value="make_ready">Lowest Make Ready</option><option value="bad">Lowest Bad</option><option value="changeover">Fastest changeover</option><option value="stability">Most consistent</option><option value="speed" disabled={!speedComparable}>Highest median speed{speedComparable ? '' : ' (units not comparable)'}</option><option value="opportunity">Largest opportunity</option></select></label><div className="ji-state-key"><span className="good">Good</span><span className="make-ready">Make Ready</span><span className="bad">Bad</span></div></div></div><div className="ji-inline-table ji-core-comparison"><table><thead><tr><th>Press</th><th>Runs</th><th>Good / MR / Bad</th><th>Typical transition</th><th>Running speed</th><th>Interruptions / h</th><th>Consistency</th><th>Comparable result</th><th>Support</th></tr></thead><tbody>{sortedPresses.map((press) => <tr key={press.pressKey} className={focusPress === press.pressKey ? 'selected' : ''}><td><button type="button" className="ji-press-focus" onClick={() => onPressChange(focusPress === press.pressKey ? undefined : press.pressKey)}>{press.displayName}</button>{focusPress === press.pressKey && <small> focus</small>}</td><td><strong>{press.runCount}</strong><small>{formatNumber(press.observedSeconds / 3600, ' h')}</small></td><td><StateBar good={press.goodPercent} makeReady={press.makeReadyPercent} bad={press.badPercent} unavailable={press.unavailablePercent} /><small>{press.goodPercent}% / {press.makeReadyPercent}% / {press.badPercent}%</small></td><td>{formatDuration(press.changeover.durationSeconds.median)}<small>N={press.changeover.transitionCount}</small></td><td>{press.running.speed ? `${formatNumber(press.running.speed.distribution.median)} ${press.running.speed.sourceUnit ?? ''}` : 'Unavailable'}</td><td>{formatNumber(press.running.interruptionsPerProductionHour)}</td><td>{consistencyLabel(press.variabilityPoints)}<small>{press.variabilityPoints === null ? '—' : `${press.variabilityPoints} pts spread`}</small></td><td>{formatNumber(press.actualVersusComparableGoodPoints, ' pts')}<small>N={press.comparableRunCount}</small></td><td><span className={`ji-support-badge ji-support--${press.support.level}`}>{supportLabel(press.support.level)}</span></td></tr>)}</tbody></table></div></section>
      <section className="panel" id="changeover-running"><div className="section-heading"><div><span className="eyebrow">Two useful phases</span><h2>Changeover vs running</h2></div><span className="section-note">Running starts at Radius stable production. Speed is descriptive telemetry, not a production-state label.</span></div><div className="ji-inline-table"><table><thead><tr><th>Press</th><th>Changeover median</th><th>Transition MR</th><th>Transition Bad</th><th>Changeover consistency</th><th>Running Good / Bad</th><th>Interruptions / h</th><th>Median running speed</th><th>Running consistency</th></tr></thead><tbody>{sortedPresses.map((press) => <tr key={press.pressKey}><td><strong>{press.displayName}</strong></td><td>{formatDuration(press.changeover.durationSeconds.median)}<small>N={press.changeover.transitionCount}</small></td><td>{formatDuration(press.changeover.makeReadySecondsPerTransition)}</td><td>{formatDuration(press.changeover.badSecondsPerTransition)}</td><td>{formatDuration(press.changeover.durationSeconds.p25)}–{formatDuration(press.changeover.durationSeconds.p75)}</td><td>{press.running.goodPercent}% / {press.running.badPercent}%</td><td>{formatNumber(press.running.interruptionsPerProductionHour)}</td><td>{press.running.speed ? `${formatNumber(press.running.speed.distribution.median)} ${press.running.speed.sourceUnit ?? ''}` : 'Unavailable'}</td><td>{consistencyLabel(press.variabilityPoints)}</td></tr>)}</tbody></table></div></section>
      <section className="panel" id="why-presses-differ"><div className="section-heading"><div><span className="eyebrow">Main Make Ready and Bad contributors</span><h2>Why presses differ</h2></div><span className="section-note">Minutes per run is primary. Select a reason for a compact affected-run summary.</span></div>{!report.radiusLossComparison.length && <div className="empty-state">No Make Ready or Bad loss reasons in this cohort.</div>}<div className="ji-loss-comparison">{report.radiusLossComparison.slice(0, 10).map((loss) => <button type="button" className={selectedLoss === loss ? 'selected' : ''} key={`${loss.eventType}-${loss.statusCode}-${loss.statusDescription}`} onClick={() => setSelectedLoss(loss)}><header><span className={`ji-radius-code ji-radius-code--${loss.eventType.toLowerCase()}`}>{loss.eventType}</span><div><strong>{loss.statusDescription}</strong><small>Exact code {loss.statusCode ?? '—'}</small></div></header><div>{loss.presses.map((item) => <span key={item.pressKey}><strong>{pressLabel(item.pressKey)}</strong><b>{formatDuration(item.secondsPerRun)}/run</b><small>{item.occurrenceCount} occurrences · median {formatDuration(item.medianEpisodeSeconds)}</small></span>)}</div></button>)}</div>{selectedLoss && <div className="ji-inline-detail"><div className="section-heading"><div><span className="eyebrow">Affected-run summary</span><h3>{selectedLoss.eventType} / {selectedLoss.statusCode ?? '—'} / {selectedLoss.statusDescription}</h3></div><button type="button" className="ji-close" onClick={() => setSelectedLoss(undefined)}>Close</button></div><div className="ji-inline-table"><table><thead><tr><th>Press</th><th>Run date</th><th>Total time</th><th>Occurrences</th><th>Exact Radius reason</th></tr></thead><tbody>{selectedLoss.presses.flatMap((press) => press.evidenceRuns.map((run) => <tr key={`${press.pressKey}-${run.runId}`} className="ji-run-row" onClick={() => inspectRun(run)}><td>{pressLabel(press.pressKey)}</td><td>{localTime(run.startUtc)}</td><td>{formatDuration(run.totalSeconds)}</td><td>{run.occurrenceCount}</td><td>{selectedLoss.eventType} / {selectedLoss.statusCode ?? '—'} / {selectedLoss.statusDescription}</td></tr>))}</tbody></table></div></div>}</section>
      <section className="panel" id="previous-job-effect"><div className="section-heading"><div><span className="eyebrow">Previous job → current job</span><h2>Does the previous job appear to matter?</h2></div><span className="section-note">Same-identity transitions and transitions across data gaps are excluded.</span></div><div className="ji-predecessor-ranking">{report.predecessorRanking.slice(0, 6).map((item) => <article key={item.transitionKey}><strong>{item.previousValue} → {item.currentValue}</strong><b>{formatDuration(item.medianTransitionSeconds)}</b><small>{item.transitionCount} runs · MR {item.makeReadyPercent}% · Bad {item.badPercent}% · {supportLabel(item.support.level)}</small></article>)}</div><div className="ji-inline-table"><table><thead><tr><th>Previous group</th><th>Current group</th><th>Runs</th><th>Presses</th><th>Median transition</th><th>Make Ready</th><th>Bad</th><th>Support</th></tr></thead><tbody>{report.transitionMatrix.map((cell) => <tr key={`${cell.previousValue}-${cell.currentValue}`}><td>{cell.previousValue}</td><td><strong>{cell.currentValue}</strong></td><td>{cell.transitionCount}</td><td>{cell.pressKeys.map(pressLabel).join(', ')}</td><td>{formatDuration(cell.durationSeconds.median)}</td><td>{formatDuration(cell.makeReadySeconds.median)}</td><td>{formatDuration(cell.badSeconds.median)}</td><td><span className={`ji-support-badge ji-support--${cell.support.level}`}>{supportLabel(cell.support.level)}</span></td></tr>)}</tbody></table></div></section>
      <section className="panel" id="historical-runs"><div className="section-heading"><div><span className="eyebrow">Run-level evidence · {localTime(report.selection.historyFromUtc)} – {localTime(report.selection.historyToUtc)} CT</span><h2>Historical production runs</h2></div><div className="ji-section-controls"><strong>{report.historicalRuns.total} matching runs</strong><label>Sort <select value={historySort} onChange={(event) => { setHistorySort(event.target.value as HistoricalRunSort); setOffset(0) }}><option value="newest">Newest</option><option value="worst_good">Worst Good %</option><option value="longest_make_ready">Longest Make Ready</option><option value="most_bad">Most Bad</option><option value="longest_transition">Longest transition</option><option value="most_interruptions">Most interruptions</option><option value="highest_speed">Highest running speed</option><option value="lowest_speed">Lowest running speed</option></select></label></div></div><div className="ji-inline-table"><table><thead><tr><th>Start (CT)</th><th>Press</th><th>{analyzeBy}</th><th>Previous</th><th>To stable</th><th>Good / MR / Bad</th><th>Interruptions</th><th>Speed</th><th>Decks</th><th>Confidence</th></tr></thead><tbody>{report.historicalRuns.items.map((run) => <tr key={run.runId} className="ji-run-row" onClick={() => inspectRun(run)} tabIndex={0} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') inspectRun(run) }}><td>{localTime(run.startUtc)}</td><td>{pressLabel(run.pressKey)}</td><td><strong>{run.identities[analyzeBy] ?? 'Unavailable'}</strong></td><td>{run.previousIdentities?.[analyzeBy] ?? '—'}</td><td>{formatDuration(run.transitionSeconds)}</td><td>{run.goodPercent}% / {run.makeReadyPercent}% / {run.badPercent}%</td><td>{run.interruptions}</td><td>{formatNumber(run.medianSpeed)}</td><td>{run.changedDeckCount ?? '—'}</td><td>{run.dataInterrupted ? 'Gap' : run.confidence}</td></tr>)}</tbody></table></div><div className="ji-paging"><button type="button" disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 50))}>Previous</button><span>{report.historicalRuns.total ? offset + 1 : 0}–{Math.min(offset + report.historicalRuns.items.length, report.historicalRuns.total)} of {report.historicalRuns.total}</span><button type="button" disabled={!report.historicalRuns.hasMore} onClick={() => setOffset(offset + 50)}>Next</button></div></section>
      <RunInspector inspector={inspector} loading={inspectorLoading} onClose={() => { setInspector(undefined); const url = new URL(window.location.href); url.searchParams.delete('run'); window.history.replaceState({}, '', `${url.pathname}?${url.searchParams}`) }} />
      <details className="panel ji-method"><summary>Coverage, timing uncertainty, and limitations</summary><div><p><strong>Boundary interpretation:</strong> the first usable metadata change may segment a run, but it is an inferred boundary. Analysis separately retains the final identity change, five-minute settled time, Radius stable-production evidence, and telemetry-derived physical behavior.</p><div className="ji-coverage-table">{report.coverage.map((press) => <article key={press.pressKey}><strong>{pressLabel(press.pressKey)}</strong>{press.fields.map((field) => <span key={field.field} title={field.limitation ?? undefined}>{field.field}: {field.capability === 'available' ? `${field.valueCoveragePercent}%` : field.capability.replaceAll('_', ' ')}</span>)}</article>)}</div><ul>{report.limitations.map((item) => <li key={item}>{item}</li>)}</ul><small>Algorithm {report.algorithmVersion} · generated {localTime(report.generatedAtUtc)} CT</small></div></details>
    </>}
  </div>
}
