import { useEffect, useMemo, useState } from 'react'
import { getFleetSpeedContext, getRadiusTimingAnalysis, getStopRestartAnalysis } from '../api/process-intelligence-api'
import { browserCategoryForClue, signalDefinition } from '../engineering-signal-catalog'
import { formatPlantDateTime } from '../time-ranges'
import type { ActivityOccurrence } from '../types/api'
import type { EngineeringClueResponse, FleetSpeedContextResponse, RadiusTimingAnalysisResponse, StopRestartResponse } from '../types/evidence'
import type { EngineeringInspectorTarget, EngineeringPin } from './EngineeringTelemetryInspector'
import { SynchronizedTimeline, type TimelineEventTrack, type TimelineIntervalTrack } from './SynchronizedTimeline'

const duration = (seconds: number | null) => seconds === null ? 'Not observed' : seconds < 60 ? `${Math.round(seconds)}s` : seconds < 3600 ? `${Math.floor(seconds / 60)}m ${Math.round(seconds % 60)}s` : `${Math.floor(seconds / 3600)}h ${Math.round(seconds % 3600 / 60)}m`
const number = (value: number | null | undefined) => value === null || value === undefined || !Number.isFinite(value) ? '—' : Math.abs(value) >= 100 ? value.toFixed(1) : value.toFixed(2)
const bucket = (value: string | null) => value === 'LOW_TRANSITION' ? 'LOW / TRANSITION · 1–600' : value === 'HIGH_SPEED_RUNNING' ? 'HIGH-SPEED RUNNING · >1000' : value === 'RUNNING' ? 'RUNNING · 600–1000' : value === 'STOPPED' ? 'STOPPED · <1' : 'Not established'
const recovery = (value: StopRestartResponse['preStopFlags'][number]['recovery']) => value.replaceAll('_', ' ').toLowerCase().replace(/^./, (character) => character.toUpperCase())
const signedDuration = (seconds: number | null) => seconds === null ? 'Insufficient matched support' : `${seconds > 0 ? '+' : seconds < 0 ? '−' : ''}${duration(Math.abs(seconds))}`
const excursionLabel = (value: StopRestartResponse['phases'] extends null ? never : NonNullable<StopRestartResponse['phases']>['restartAttempts'][number]['classification']) => value === 'BRIEF_LOW_SPEED_EXCURSION' ? 'Brief low-speed excursion' : value === 'FAILED_RUNNING_ATTEMPT' ? 'Failed running attempt' : value === 'SUSTAINED_PHYSICAL_RUNNING_RESUMED' ? 'Sustained physical running resumed' : 'Restart excursion'

function phaseTracks(data: StopRestartResponse): { intervals: TimelineIntervalTrack[]; events: TimelineEventTrack[] } {
  if (!data.phases) return { intervals: [], events: [] }
  const phases = data.phases
  const items = [
    phases.stableRunningBefore.fromUtc && phases.stableRunningBefore.toUtc ? { id: 'stable-before', startUtc: phases.stableRunningBefore.fromUtc, endUtc: phases.stableRunningBefore.toUtc, label: 'Stable physical running before', details: bucket(phases.stableRunningBefore.bucket), className: 'stop-phase stop-phase--running' } : null,
    phases.deceleration.fromUtc ? { id: 'deceleration', startUtc: phases.deceleration.fromUtc, endUtc: phases.deceleration.toUtc ?? data.physicalStopMatch.selected?.atUtc ?? phases.deceleration.fromUtc, label: 'Observed lead-up / deceleration', details: 'Speed left its prior physical running bucket', className: 'stop-phase stop-phase--leadup' } : null,
    { id: 'stopped', startUtc: phases.stopped.fromUtc, endUtc: phases.stopped.toUtc ?? data.analysisWindow.toUtc, label: 'STOPPED', details: 'Actual observed speed below 1', className: 'stop-phase stop-phase--stopped' },
    ...phases.restartAttempts.flatMap((attempt) => attempt.endUtc ? [{ id: `attempt-${attempt.attempt}`, startUtc: attempt.startUtc, endUtc: attempt.endUtc, label: `${excursionLabel(attempt.classification)} ${attempt.attempt}`, details: `Maximum observed speed ${number(attempt.maximumObservedSpeed)} · ${bucket(attempt.highestBucket)}`, className: `stop-phase ${attempt.sustainedRunning ? 'stop-phase--running' : 'stop-phase--restart'}` }] : []),
    phases.sustainedRunningAgain.fromUtc && phases.sustainedRunningAgain.toUtc ? { id: 'running-again', startUtc: phases.sustainedRunningAgain.fromUtc, endUtc: phases.sustainedRunningAgain.toUtc, label: 'Sustained physical running resumed', details: bucket(phases.sustainedRunningAgain.bucket), className: 'stop-phase stop-phase--running' } : null,
  ].filter((item): item is NonNullable<typeof item> => Boolean(item) && Date.parse(item!.endUtc) > Date.parse(item!.startUtc))
  const markers = [
    data.physicalStopMatch.selected ? { id: 'physical-stop', atUtc: data.physicalStopMatch.selected.atUtc, label: 'Observed physical stop', detail: `Actual speed ${number(data.physicalStopMatch.selected.observedSpeed)}`, category: 'physical-stop' } : null,
    { id: 'radius-entry', atUtc: data.occurrence.startUtc, label: 'Radius recorded', detail: data.occurrence.exactIdentities.map(({ eventType, statusCode, statusDescription }) => `${eventType} / ${statusCode ?? '—'} / ${statusDescription}`).join('; '), category: 'radius-entry' },
    phases.sustainedRunningConfirmedAtUtc ? { id: 'running-confirmed', atUtc: phases.sustainedRunningConfirmedAtUtc, label: 'Sustained physical running confirmed', detail: 'Separate 120-second physical-running confirmation policy', category: 'physical-restart' } : null,
  ].filter((item): item is NonNullable<typeof item> => Boolean(item))
  return { intervals: [{ id: 'physical-phases', label: 'Physical phases', intervals: items }], events: [{ id: 'physical-markers', label: 'Observed markers', events: markers }] }
}

export function StopRestartAnalysisPanel({ occurrence, peers, clues, pins, onView, onPin, onAnalysis }: { occurrence: ActivityOccurrence; peers: ActivityOccurrence[]; clues: EngineeringClueResponse; pins: EngineeringPin[]; onView(target: EngineeringInspectorTarget): void; onPin(pin: EngineeringPin): void; onAnalysis(value?: StopRestartResponse): void }) {
  const [data, setData] = useState<StopRestartResponse>()
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(false)
  const [radiusTiming, setRadiusTiming] = useState<RadiusTimingAnalysisResponse>()
  const [radiusTimingLoading, setRadiusTimingLoading] = useState(false)
  const [fleetRequested, setFleetRequested] = useState(false)
  const [fleet, setFleet] = useState<FleetSpeedContextResponse>()
  const [fleetLoading, setFleetLoading] = useState(false)
  const candidates = useMemo(() => {
    const clueCandidates = clues.signalClues.filter(({ isClue, signalType }) => isClue && signalType === 'continuous').map(({ canonicalId, deckNumber, friendlyName, signalType, category }) => ({ canonicalId, ...(deckNumber === null ? {} : { deckNumber }), friendlyName, signalType, category, source: 'clue' as const }))
    const pinCandidates = pins.flatMap((pin) => { const definition = signalDefinition(pin.canonicalId); return definition?.signalType === 'continuous' ? [{ ...pin, friendlyName: definition.friendlyName, signalType: definition.signalType, category: definition.clueCategory, source: 'pin' as const }] : [] })
    return [...clueCandidates, ...pinCandidates].filter((item, index, all) => all.findIndex((candidate) => candidate.canonicalId === item.canonicalId && candidate.deckNumber === item.deckNumber) === index)
  }, [clues.signalClues, pins])

  useEffect(() => {
    const occurrenceId = occurrence.occurrenceId
    const controller = new AbortController(); setLoading(true); setError(false); setData(undefined); setRadiusTiming(undefined); setFleetRequested(false); setFleet(undefined); onAnalysis(undefined)
    void getStopRestartAnalysis(occurrence.pressKey, occurrence, candidates, controller.signal).then((value) => { if (!controller.signal.aborted && value.occurrence.occurrenceId === occurrenceId) { setData(value); onAnalysis(value) } }).catch(() => { if (!controller.signal.aborted) setError(true) }).finally(() => { if (!controller.signal.aborted) setLoading(false) })
    return () => controller.abort()
  }, [occurrence.occurrenceId, candidates.map(({ canonicalId, deckNumber }) => `${canonicalId}:${deckNumber ?? ''}`).join('|')])

  const primaryIdentity = occurrence.exactIdentities[0]
  const timingPeers = useMemo(() => primaryIdentity ? peers.filter(({ exactIdentities }) => exactIdentities.some(({ eventType, statusCode, statusDescription }) => eventType === primaryIdentity.eventType && statusCode === primaryIdentity.statusCode && statusDescription === primaryIdentity.statusDescription)).slice(0, 30) : [], [peers, primaryIdentity?.eventType, primaryIdentity?.statusCode, primaryIdentity?.statusDescription])
  useEffect(() => {
    if (!data || !primaryIdentity || timingPeers.length < 2) return
    const controller = new AbortController(); setRadiusTimingLoading(true); setRadiusTiming(undefined)
    void getRadiusTimingAnalysis(primaryIdentity, timingPeers, controller.signal).then((value) => { if (!controller.signal.aborted) setRadiusTiming(value) }).catch(() => undefined).finally(() => { if (!controller.signal.aborted) setRadiusTimingLoading(false) })
    return () => controller.abort()
  }, [data?.occurrence.occurrenceId, timingPeers.map(({ occurrenceId }) => occurrenceId).join('|')])

  useEffect(() => {
    if (!data || !fleetRequested) return
    const controller = new AbortController(); setFleetLoading(true); setFleet(undefined)
    const pressKeys = [...new Set(peers.map(({ pressKey }) => pressKey))].slice(0, 6)
    void getFleetSpeedContext(data.speedContext.referencePeriod.fromUtc, data.speedContext.referencePeriod.toUtc, pressKeys, controller.signal).then((value) => { if (!controller.signal.aborted) setFleet(value) }).catch(() => undefined).finally(() => { if (!controller.signal.aborted) setFleetLoading(false) })
    return () => controller.abort()
  }, [data?.occurrence.occurrenceId, fleetRequested])

  if (loading) return <section className="stop-restart-analysis"><div className="scope-progress" role="status"><i />Building physical stop chronology and comparable-speed reference…</div></section>
  if (error || !data) return <section className="stop-restart-analysis"><p className="message message--warning">Stop & Restart Analysis is temporarily unavailable. Telemetry Clues and the Engineering Inspector remain usable.</p></section>
  const tracks = phaseTracks(data)
  return <section className="stop-restart-analysis" aria-labelledby="stop-restart-title" data-stop-match={data.physicalStopMatch.status}>
    <div className="section-heading"><div><p className="eyebrow">Primary physical interpretation</p><h2 id="stop-restart-title">Stop & Restart Analysis</h2><p>Physical speed anchors this chronology. Radius remains the synchronized operator-recorded explanation.</p></div><span className={`stop-match stop-match--${data.physicalStopMatch.status.toLowerCase()}`}>{data.physicalStopMatch.status.replaceAll('_', ' ')}</span></div>
    <div className="stop-radius-facts"><article><span>Radius recorded</span><strong>{data.occurrence.exactIdentities.map(({ eventType, statusCode }) => `${eventType} / ${statusCode ?? '—'}`).join('; ')}</strong><small>{data.occurrence.exactIdentities.map(({ statusDescription }) => statusDescription).join('; ')}</small></article><article><span>Classified as</span><strong>{data.occurrence.operationalGroupName}</strong><small>{data.occurrence.processFamilyName}</small></article><article><span>Physical association</span><strong>{data.physicalStopMatch.status.replaceAll('_', ' ')}</strong><small>{data.radiusTiming.wording}</small></article></div>
    {data.physicalStopMatch.status === 'AMBIGUOUS' && <div className="message"><b>Multiple reasonable physical stops were observed.</b> {data.physicalStopMatch.candidates.map((candidate) => `${formatPlantDateTime(candidate.atUtc)} CT (${candidate.radiusOffsetSeconds >= 0 ? '+' : ''}${Math.round(candidate.radiusOffsetSeconds)}s)`).join(' · ')}</div>}
    {data.physicalStopMatch.status === 'NO_PHYSICAL_STOP_FOUND' && <p className="empty-state">No transition into observed speed below 1 was found in the bounded −30/+10 minute association window. Generic Telemetry Clues remain available below.</p>}
    {data.physicalStopMatch.status === 'INSUFFICIENT_SPEED_EVIDENCE' && <p className="empty-state">There was not enough timestamped actual-speed evidence on both sides of Radius entry to associate a physical stop.</p>}
    {data.phases && <>
      <section className="stop-subsection"><h3>Physical timeline</h3><SynchronizedTimeline fromUtc={data.analysisWindow.fromUtc} toUtc={data.analysisWindow.toUtc} ariaLabel="Physical stop and restart chronology" intervalTracks={tracks.intervals} eventTracks={tracks.events} minimumCanvasWidth={720} /></section>
      <div className="stop-analysis-grid"><section className="stop-subsection"><h3>Speed operating context</h3><dl className="stop-speed-current"><div><dt>Pre-stop bucket</dt><dd>{bucket(data.speedContext.preStopBucket)}</dd></div><div><dt>Median pre-stop speed</dt><dd>{number(data.phases.stableRunningBefore.stats?.median)}</dd></div><div><dt>Observed continuous duration</dt><dd>{duration(data.phases.stableRunningBefore.durationSeconds)}</dd></div><div><dt>Same-press reference percentile</dt><dd>{data.speedContext.currentPercentile === null ? 'Insufficient reference' : `P${data.speedContext.currentPercentile}`}</dd></div></dl><div className="speed-bucket-cards">{data.speedContext.samePressBuckets.map((item) => <article key={item.bucket}><strong>{bucket(item.bucket)}</strong><span>{item.observationCount} observations</span><small>{item.stats ? `median ${number(item.stats.median)} · P25/P75 ${number(item.stats.p25)}–${number(item.stats.p75)}` : 'Insufficient observations'}</small><small>{duration(item.observedDurationSeconds)} bounded observed duration · {item.sustainedSpanCount} spans</small></article>)}</div><p className="quiet-copy">{data.referenceMetadata.message}</p><button type="button" className="secondary-action" disabled={fleetLoading || Boolean(fleet)} onClick={() => setFleetRequested(true)}>{fleetLoading ? 'Loading bounded fleet speed context…' : fleet ? 'Fleet speed context loaded' : 'Load fleet speed context'}</button>{fleet && <div className="fleet-speed-context"><p className="quiet-copy">Speed is compared descriptively across presses; rarely observed ranges remain descriptive evidence.</p>{fleet.presses.map((press) => <article key={press.pressKey}><strong>{press.pressKey.replace('press', 'Press ')}</strong>{press.status === 'AVAILABLE' ? press.buckets.map((item) => <small key={item.bucket}>{bucket(item.bucket)} · {item.observationCount} obs · {item.sharePercent.toFixed(1)}%</small>) : <small>Temporarily unavailable</small>}</article>)}<p>{fleet.rawEngineeringComparison.message}</p></div>}</section>
      <section className="stop-subsection"><h3>Stop / Restart Sequence</h3>{data.phases.restartAttempts.length ? <ol className="restart-attempts">{data.phases.restartAttempts.map((attempt) => <li key={attempt.attempt}><strong>{excursionLabel(attempt.classification)} {attempt.attempt}</strong><span>{formatPlantDateTime(attempt.startUtc)} CT · max {number(attempt.maximumObservedSpeed)} · {duration(attempt.durationSeconds)} · {attempt.speedObservationCount} speed observations</span><small>{attempt.sustainedRunning ? 'Sustained physical running was confirmed' : attempt.failedRunningAttempt ? 'Reached ≥600, then returned to STOPPED without a sustained physical-running confirmation' : attempt.returnedToStopped ? `Returned to STOPPED · motion evidence ${attempt.motionSupportsMovement ? 'supports movement' : 'did not independently show movement'}` : 'No sustained physical-running confirmation in the bounded window'}</small></li>)}</ol> : <p className="empty-state">No physical restart excursion was observed in the bounded detailed window.</p>}</section></div>
      {data.preStopFlags.length ? <section className="stop-subsection potential-flags"><div className="section-heading"><div><p className="eyebrow">High-precision investigation heuristic</p><h3>Potential Pre-Stop Flags</h3><p>Only evidence observed while still in the prior physical-running bucket is compared with this same press at the same speed bucket.</p></div><span>{data.preStopFlags.length} of maximum {data.referenceMetadata.flagLimit}</span></div><div className="prestop-flag-grid">{data.preStopFlags.map((flag) => <article key={`${flag.canonicalId}:${flag.deckNumber ?? ''}`}><header><span>{flag.deckNumber === null ? 'Machine' : `Deck ${flag.deckNumber}`}</span><h4>{flag.friendlyName}</h4><code>{flag.canonicalId}</code></header><p>{flag.wording}</p><div className="flag-comparison"><div><span>Pre-stop</span><strong>{number(flag.current.median)}</strong><small>{flag.current.count} observations</small></div><div><span>Comparable-speed reference</span><strong>{number(flag.reference.median)}</strong><small>P05/P95 {number(flag.reference.p05)}–{number(flag.reference.p95)} · {flag.reference.count} observations</small></div><div><span>After restart</span><strong>{number(flag.afterRestart?.median)}</strong><small>{recovery(flag.recovery)}</small></div></div><footer><span>{flag.direction === 'ABOVE' ? 'Observed above' : 'Observed below'} historical reference · {bucket(flag.speedBucket)}</span><div><button type="button" className="secondary-action" onClick={() => onView({ scope: flag.deckNumber === null ? 'machine' : 'deck', category: browserCategoryForClue(flag.category, flag.canonicalId), canonicalId: flag.canonicalId, ...(flag.deckNumber === null ? {} : { deckNumber: flag.deckNumber }), requestId: Date.now() })}>View Trace</button><button type="button" onClick={() => onPin({ canonicalId: flag.canonicalId, ...(flag.deckNumber === null ? {} : { deckNumber: flag.deckNumber }) })}>Pin</button></div></footer></article>)}</div></section> : <section className="stop-subsection no-prestop-flag"><p>{data.noFlagMessage ?? 'Comparable pre-stop evidence was not available for a conservative automatic flag.'}</p><small>The Engineering Inspector remains available for direct trace review.</small></section>}
      <section className="stop-subsection"><h3>Stop / Restart Context</h3><p className="quiet-copy">Raw state and Radius evidence remain context; they are not automatically ranked as pre-stop flags.</p><ol className="stop-sequence">{data.stopRestartContext.map((event, index) => <li key={`${event.atUtc}:${index}`}><time>{formatPlantDateTime(event.atUtc)} CT</time><span><b>{event.kind.replace('_', ' ')}</b>{event.label}</span></li>)}</ol></section>
      <section className="stop-subsection radius-timing-context"><h3>Radius Timing Context</h3>{radiusTimingLoading ? <div className="scope-progress" role="status"><i />Matching similar exact Radius occurrences to observed physical stops…</div> : radiusTiming ? <><p><strong>{radiusTiming.exactIdentity.eventType} / {radiusTiming.exactIdentity.statusCode ?? '—'} / {radiusTiming.exactIdentity.statusDescription}</strong></p><div className="radius-timing-summary"><article><span>Matched physical stops</span><strong>{radiusTiming.matchedCount} / {radiusTiming.occurrenceCount}</strong></article><article><span>Radius before / near / after</span><strong>{radiusTiming.beforeCount} / {radiusTiming.nearCount} / {radiusTiming.afterCount}</strong></article><article><span>Median Radius-entry offset</span><strong>{signedDuration(radiusTiming.medianOffsetSeconds)}</strong><small>IQR {radiusTiming.iqrSeconds === null ? '—' : duration(radiusTiming.iqrSeconds)}</small></article></div><div className="radius-timing-presses">{radiusTiming.byPress.map((press) => <article key={press.pressKey}><strong>{press.displayName}</strong><span>{press.matchedCount} / {press.occurrenceCount} matched physical stop</span><small>{press.medianSupport === 'SUPPORTED' ? `median Radius offset ${signedDuration(press.medianOffsetSeconds)}` : 'Median requires 3 matched occurrences'}</small></article>)}</div><p className="quiet-copy">Offsets describe when Radius was recorded relative to observed physical speed. They do not imply when an entry should occur.</p></> : <p className="empty-state">{timingPeers.length < 2 ? 'No additional loaded occurrence of this exact Radius identity is available in the selected analysis range.' : 'Radius timing context is temporarily unavailable; the focused occurrence remains usable.'}</p>}</section>
    </>}
    <details className="analysis-method"><summary>Reference support and request details</summary><p>{data.referenceMetadata.status.replaceAll('_', ' ')} · {data.referenceMetadata.observedScreenCandidateCount} of {data.referenceMetadata.currentScreenCandidateCount} eligible bounded current-window candidates observed · {data.referenceMetadata.knownInactiveDeckCandidatesExcluded} known-inactive deck candidates excluded · {data.referenceMetadata.candidateCount} historical candidates · {data.referenceMetadata.requestCount} sequential reference requests · {data.referenceMetadata.excludedObservationsWithoutFreshSpeed} signal observations excluded without speed evidence no older than three minutes.</p><p>Historical slots: {Object.entries(data.referenceMetadata.selectionCounts).filter(([, count]) => count > 0).map(([source, count]) => `${source.replaceAll('_', ' ')} ${count}`).join(' · ') || 'none'}.</p><p>Response {Math.round(data.performance.responsePayloadBytes / 1024)} KB · server analysis {Math.round(data.performance.totalMs)} ms · cache {data.referenceMetadata.cache}.</p></details>
  </section>
}
